// <auto-generated />
using System;
using HospitalManagement.Modules.Patients.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HospitalManagement.Modules.Patients.Infrastructure.Persistence.Migrations;

[DbContext(typeof(PatientsDbContext))]
[Migration("20260827235500_InitialPatients")]
partial class InitialPatients
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("patients")
            .HasAnnotation("ProductVersion", "9.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("HospitalManagement.Modules.Patients.Domain.Patient", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<DateTime>("CreatedAtUtc")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at_utc");

            b.Property<DateOnly>("DateOfBirth")
                .HasColumnType("date")
                .HasColumnName("date_of_birth");

            b.Property<string>("Email")
                .HasMaxLength(256)
                .HasColumnType("character varying(256)")
                .HasColumnName("email");

            b.Property<string>("FirstName")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("character varying(128)")
                .HasColumnName("first_name");

            b.Property<string>("Gender")
                .IsRequired()
                .HasMaxLength(16)
                .HasColumnType("character varying(16)")
                .HasColumnName("gender");

            b.Property<bool>("IsActive")
                .HasColumnType("boolean")
                .HasColumnName("is_active");

            b.Property<string>("LastName")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("character varying(128)")
                .HasColumnName("last_name");

            b.Property<string>("MedicalRecordNumber")
                .IsRequired()
                .HasMaxLength(32)
                .HasColumnType("character varying(32)")
                .HasColumnName("medical_record_number");

            b.Property<string>("NationalIdSynthetic")
                .HasMaxLength(32)
                .HasColumnType("character varying(32)")
                .HasColumnName("national_id_synthetic");

            b.Property<Guid>("PersonId")
                .HasColumnType("uuid")
                .HasColumnName("person_id");

            b.Property<string>("PhoneNumber")
                .HasMaxLength(32)
                .HasColumnType("character varying(32)")
                .HasColumnName("phone_number");

            b.Property<DateTime?>("UpdatedAtUtc")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_at_utc");

            b.Property<long>("Version")
                .IsConcurrencyToken()
                .HasColumnType("bigint")
                .HasColumnName("version");

            b.HasKey("Id");

            b.HasIndex("NationalIdSynthetic")
                .HasDatabaseName("ix_patient_records_national_id");

            b.HasIndex("PersonId")
                .HasDatabaseName("ix_patient_records_person_id");

            b.HasIndex("MedicalRecordNumber")
                .IsUnique()
                .HasDatabaseName("ux_patient_records_mrn");

            b.HasIndex("LastName", "FirstName", "DateOfBirth")
                .HasDatabaseName("ix_patient_records_name_dob");

            b.ToTable("patient_records", "patients");
        });

        modelBuilder.Entity("HospitalManagement.Modules.Patients.Domain.Patient", b =>
        {
            b.OwnsOne("HospitalManagement.Modules.Patients.Domain.AddressValue", "Address", b1 =>
            {
                b1.Property<Guid>("PatientId")
                    .HasColumnType("uuid");

                b1.Property<string>("City")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("address_city");

                b1.Property<string>("District")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("address_district");

                b1.Property<string>("Line1")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("address_line1");

                b1.Property<string>("PostalCode")
                    .HasMaxLength(16)
                    .HasColumnType("character varying(16)")
                    .HasColumnName("address_postal_code");

                b1.HasKey("PatientId");

                b1.ToTable("patient_records", "patients");

                b1.WithOwner()
                    .HasForeignKey("PatientId");
            });

            b.OwnsOne("HospitalManagement.Modules.Patients.Domain.CommunicationPreferencesValue", "CommunicationPreferences", b1 =>
            {
                b1.Property<Guid>("PatientId")
                    .HasColumnType("uuid");

                b1.Property<bool>("AllowEmail")
                    .HasColumnType("boolean")
                    .HasColumnName("pref_allow_email");

                b1.Property<bool>("AllowSms")
                    .HasColumnType("boolean")
                    .HasColumnName("pref_allow_sms");

                b1.Property<string>("PreferredLanguage")
                    .IsRequired()
                    .HasMaxLength(8)
                    .HasColumnType("character varying(8)")
                    .HasColumnName("pref_language");

                b1.HasKey("PatientId");

                b1.ToTable("patient_records", "patients");

                b1.WithOwner()
                    .HasForeignKey("PatientId");
            });

            b.OwnsOne("HospitalManagement.Modules.Patients.Domain.EmergencyContactValue", "EmergencyContact", b1 =>
            {
                b1.Property<Guid>("PatientId")
                    .HasColumnType("uuid");

                b1.Property<string>("FullName")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)")
                    .HasColumnName("emergency_contact_name");

                b1.Property<string>("PhoneNumber")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("emergency_contact_phone");

                b1.Property<string>("Relationship")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("emergency_contact_relationship");

                b1.HasKey("PatientId");

                b1.ToTable("patient_records", "patients");

                b1.WithOwner()
                    .HasForeignKey("PatientId");
            });

            b.Navigation("Address");
            b.Navigation("CommunicationPreferences")
                .IsRequired();
            b.Navigation("EmergencyContact");
        });
#pragma warning restore 612, 618
    }
}
