// <auto-generated />
using System;
using HospitalManagement.Modules.Reporting.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HospitalManagement.Modules.Reporting.Infrastructure.Persistence.Migrations;

[DbContext(typeof(ReportingDbContext))]
[Migration("20260904000100_InitialReportingSchema")]
partial class InitialReportingSchema
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("reporting")
            .HasAnnotation("ProductVersion", "10.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("HospitalManagement.Modules.Reporting.Domain.BedOccupancyMetric", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<int>("AvailableBeds")
                    .HasColumnType("integer");

                b.Property<DateOnly>("Date")
                    .HasColumnType("date");

                b.Property<Guid>("DepartmentId")
                    .HasColumnType("uuid");

                b.Property<string>("DepartmentName")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("character varying(150)");

                b.Property<DateTime>("LastUpdatedUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("OccupiedBeds")
                    .HasColumnType("integer");

                b.Property<int>("PendingTransferCount")
                    .HasColumnType("integer");

                b.Property<int>("TotalBeds")
                    .HasColumnType("integer");

                b.Property<string>("WardType")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.HasKey("Id");

                b.HasIndex("Date");

                b.HasIndex("DepartmentId");

                b.HasIndex("Date", "DepartmentId", "WardType")
                    .IsUnique();

                b.ToTable("bed_occupancy_metrics", "reporting");
            });

        modelBuilder.Entity("HospitalManagement.Modules.Reporting.Domain.DailyOutpatientMetric", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<int>("CancelledCount")
                    .HasColumnType("integer");

                b.Property<int>("CheckedInCount")
                    .HasColumnType("integer");

                b.Property<int>("CompletedCount")
                    .HasColumnType("integer");

                b.Property<DateOnly>("Date")
                    .HasColumnType("date");

                b.Property<Guid>("DepartmentId")
                    .HasColumnType("uuid");

                b.Property<string>("DepartmentName")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("character varying(150)");

                b.Property<Guid?>("DoctorId")
                    .HasColumnType("uuid");

                b.Property<string>("DoctorName")
                    .HasMaxLength(150)
                    .HasColumnType("character varying(150)");

                b.Property<int>("InProgressCount")
                    .HasColumnType("integer");

                b.Property<DateTime>("LastUpdatedUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("NoShowCount")
                    .HasColumnType("integer");

                b.Property<int>("ScheduledCount")
                    .HasColumnType("integer");

                b.Property<int>("TotalAppointments")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.HasIndex("Date");

                b.HasIndex("DepartmentId");

                b.HasIndex("Date", "DepartmentId", "DoctorId")
                    .IsUnique();

                b.ToTable("daily_outpatient_metrics", "reporting");
            });

        modelBuilder.Entity("HospitalManagement.Modules.Reporting.Domain.DiagnosticWorkloadMetric", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<double>("AvgTurnaroundMinutes")
                    .HasColumnType("double precision");

                b.Property<int>("CriticalCount")
                    .HasColumnType("integer");

                b.Property<DateOnly>("Date")
                    .HasColumnType("date");

                b.Property<int>("FinalizedCount")
                    .HasColumnType("integer");

                b.Property<DateTime>("LastUpdatedUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("ModalityOrSection")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.Property<int>("PendingSpecimenCount")
                    .HasColumnType("integer");

                b.Property<int>("ProcessingCount")
                    .HasColumnType("integer");

                b.Property<int>("TotalOrders")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.HasIndex("Date");

                b.HasIndex("Date", "ModalityOrSection")
                    .IsUnique();

                b.ToTable("diagnostic_workload_metrics", "reporting");
            });

        modelBuilder.Entity("HospitalManagement.Modules.Reporting.Domain.PharmacyDispensingMetric", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateOnly>("Date")
                    .HasColumnType("date");

                b.Property<int>("DispensedCount")
                    .HasColumnType("integer");

                b.Property<DateTime>("LastUpdatedUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("LowStockItemCount")
                    .HasColumnType("integer");

                b.Property<int>("NearExpiryLotCount")
                    .HasColumnType("integer");

                b.Property<int>("PendingDispenseCount")
                    .HasColumnType("integer");

                b.Property<int>("TotalPrescriptions")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.HasIndex("Date")
                    .IsUnique();

                b.ToTable("pharmacy_dispensing_metrics", "reporting");
            });

        modelBuilder.Entity("HospitalManagement.Modules.Reporting.Domain.ProjectionCheckpoint", b =>
            {
                b.Property<string>("ProjectionName")
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.Property<string>("LastError")
                    .HasMaxLength(2000)
                    .HasColumnType("character varying(2000)");

                b.Property<long>("LastProcessedPosition")
                    .HasColumnType("bigint");

                b.Property<DateTime>("LastProcessedTimestampUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("character varying(30)");

                b.Property<int>("Version")
                    .HasColumnType("integer");

                b.HasKey("ProjectionName");

                b.ToTable("projection_checkpoints", "reporting");
            });

        modelBuilder.Entity("HospitalManagement.Modules.Reporting.Domain.ProjectionProcessedEvent", b =>
            {
                b.Property<Guid>("EventId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTime>("ProcessedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("ProjectionName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.HasKey("EventId");

                b.HasIndex("ProjectionName", "ProcessedAtUtc");

                b.ToTable("projection_processed_events", "reporting");
            });
#pragma warning restore 612, 618
    }
}
