namespace HospitalManagement.BuildingBlocks.Authorization;

public static class HospitalPermissionCatalog
{
    public static readonly IReadOnlyList<PermissionDefinition> All =
    [
        // Identity & Organization
        new(HospitalPermissions.Identity.ProfileViewOwn, "Identity", "Kendi profil bilgilerini görüntüleme",
            [HospitalRoles.Patient, HospitalRoles.Doctor, HospitalRoles.Nurse, HospitalRoles.ChiefMedicalOfficer, HospitalRoles.RegistrationStaff, HospitalRoles.LaboratoryStaff, HospitalRoles.RadiologyStaff, HospitalRoles.Pharmacist, HospitalRoles.SystemAdministrator, HospitalRoles.HospitalManager]),
        new(HospitalPermissions.Identity.ProfileEditOwn, "Identity", "Kendi profil bilgilerini düzenleme",
            [HospitalRoles.Patient, HospitalRoles.Doctor, HospitalRoles.Nurse, HospitalRoles.ChiefMedicalOfficer, HospitalRoles.RegistrationStaff, HospitalRoles.LaboratoryStaff, HospitalRoles.RadiologyStaff, HospitalRoles.Pharmacist, HospitalRoles.SystemAdministrator, HospitalRoles.HospitalManager]),
        new(HospitalPermissions.Identity.UserInviteStaff, "Identity", "Personel daveti oluşturma",
            [HospitalRoles.SystemAdministrator]),
        new(HospitalPermissions.Identity.UserDisable, "Identity", "Kullanıcı hesabını devre dışı bırakma",
            [HospitalRoles.SystemAdministrator]),
        new(HospitalPermissions.Identity.RoleAssign, "Identity", "Kullanıcıya rol atama",
            [HospitalRoles.SystemAdministrator]),
        new(HospitalPermissions.Identity.PermissionAssign, "Identity", "Kullanıcıya doğrudan izin atama",
            [HospitalRoles.SystemAdministrator]),
        new(HospitalPermissions.Organization.View, "Organization", "Hastane, şube ve bölüm bilgilerini görüntüleme",
            [HospitalRoles.Doctor, HospitalRoles.Nurse, HospitalRoles.ChiefMedicalOfficer, HospitalRoles.RegistrationStaff, HospitalRoles.LaboratoryStaff, HospitalRoles.RadiologyStaff, HospitalRoles.Pharmacist, HospitalRoles.HospitalManager]),
        new(HospitalPermissions.Organization.Manage, "Organization", "Hastane, şube ve bölüm yapılandırmasını yönetme",
            [HospitalRoles.SystemAdministrator]),

        // Patient & Appointment
        new(HospitalPermissions.Patient.ViewOwn, "Patient", "Hasta portalında kendi kaydını görüntüleme",
            [HospitalRoles.Patient]),
        new(HospitalPermissions.Patient.Search, "Patient", "Hasta arama",
            [HospitalRoles.RegistrationStaff, HospitalRoles.Doctor, HospitalRoles.Nurse, HospitalRoles.ChiefMedicalOfficer]),
        new(HospitalPermissions.Patient.DemographicsView, "Patient", "Hasta demografik bilgilerini görüntüleme",
            [HospitalRoles.RegistrationStaff, HospitalRoles.Doctor, HospitalRoles.Nurse, HospitalRoles.ChiefMedicalOfficer]),
        new(HospitalPermissions.Patient.DemographicsCreate, "Patient", "Yeni hasta kaydı oluşturma",
            [HospitalRoles.RegistrationStaff]),
        new(HospitalPermissions.Patient.DemographicsEdit, "Patient", "Hasta demografik bilgilerini düzenleme",
            [HospitalRoles.RegistrationStaff, HospitalRoles.ChiefMedicalOfficer]),
        new(HospitalPermissions.Appointment.ViewOwn, "Appointment", "Hasta portalında kendi randevularını görüntüleme",
            [HospitalRoles.Patient]),
        new(HospitalPermissions.Appointment.BookOwn, "Appointment", "Hasta portalında kendi adına randevu alma",
            [HospitalRoles.Patient]),
        new(HospitalPermissions.Appointment.ManageOwn, "Appointment", "Hasta portalında kendi randevusunu yönetme/iptal etme",
            [HospitalRoles.Patient]),
        new(HospitalPermissions.Appointment.Manage, "Appointment", "Kayıt personeli randevu yönetimi",
            [HospitalRoles.RegistrationStaff]),
        new(HospitalPermissions.Appointment.ScheduleManage, "Appointment", "Doktor çalışma takvimini yönetme",
            [HospitalRoles.Doctor, HospitalRoles.ChiefMedicalOfficer, HospitalRoles.RegistrationStaff]),
        new(HospitalPermissions.Appointment.CheckIn, "Appointment", "Randevu check-in ve sıra kabul işlemi",
            [HospitalRoles.RegistrationStaff]),

        // Clinical Records
        new(HospitalPermissions.ClinicalRecords.EncounterView, "ClinicalRecords", "Klinik karşılaşma detaylarını görüntüleme",
            [HospitalRoles.Doctor, HospitalRoles.Nurse, HospitalRoles.ChiefMedicalOfficer]),
        new(HospitalPermissions.ClinicalRecords.EncounterStart, "ClinicalRecords", "Klinik karşılaşma başlatma",
            [HospitalRoles.Doctor, HospitalRoles.ChiefMedicalOfficer]),
        new(HospitalPermissions.ClinicalRecords.EncounterComplete, "ClinicalRecords", "Klinik karşılaşmayı tamamlama",
            [HospitalRoles.Doctor, HospitalRoles.ChiefMedicalOfficer]),
        new(HospitalPermissions.ClinicalRecords.ObservationRecordVital, "ClinicalRecords", "Vital bulguları kaydetme",
            [HospitalRoles.Nurse, HospitalRoles.Doctor, HospitalRoles.ChiefMedicalOfficer]),
        new(HospitalPermissions.ClinicalRecords.ClinicalNoteEditDraft, "ClinicalRecords", "Taslak klinik not düzenleme",
            [HospitalRoles.Doctor, HospitalRoles.Nurse, HospitalRoles.ChiefMedicalOfficer]),
        new(HospitalPermissions.ClinicalRecords.ClinicalNoteSign, "ClinicalRecords", "Klinik not imzalama",
            [HospitalRoles.Doctor, HospitalRoles.Nurse, HospitalRoles.ChiefMedicalOfficer]),
        new(HospitalPermissions.ClinicalRecords.ClinicalNoteCorrect, "ClinicalRecords", "İmzalı klinik not düzeltme",
            [HospitalRoles.Doctor, HospitalRoles.ChiefMedicalOfficer]),
        new(HospitalPermissions.ClinicalRecords.ClinicalNoteReopen, "ClinicalRecords", "Kapatılmış notu yeniden açma",
            [HospitalRoles.ChiefMedicalOfficer]),
        new(HospitalPermissions.ClinicalRecords.DiagnosisRecord, "ClinicalRecords", "Tanı kaydetme",
            [HospitalRoles.Doctor, HospitalRoles.ChiefMedicalOfficer]),
        new(HospitalPermissions.ClinicalRecords.ConsultationRequest, "ClinicalRecords", "Konsültasyon isteme",
            [HospitalRoles.Doctor, HospitalRoles.ChiefMedicalOfficer]),
        new(HospitalPermissions.ClinicalRecords.ConsultationRespond, "ClinicalRecords", "Konsültasyon yanıtlama",
            [HospitalRoles.Doctor, HospitalRoles.ChiefMedicalOfficer]),
        new(HospitalPermissions.ClinicalRecords.ClinicalAttachmentUpload, "ClinicalRecords", "Klinik ek dosya yükleme",
            [HospitalRoles.Doctor, HospitalRoles.Nurse, HospitalRoles.ChiefMedicalOfficer]),

        // Pharmacy & Inventory
        new(HospitalPermissions.Pharmacy.MedicationCatalogView, "Pharmacy", "İlaç kataloğunu arama ve görüntüleme",
            [HospitalRoles.Doctor, HospitalRoles.Nurse, HospitalRoles.Pharmacist, HospitalRoles.ChiefMedicalOfficer, HospitalRoles.RegistrationStaff, HospitalRoles.HospitalManager, HospitalRoles.SystemAdministrator]),
        new(HospitalPermissions.Pharmacy.MedicationCatalogManage, "Pharmacy", "İlaç kataloğunu içe aktarma ve yönetme",
            [HospitalRoles.Pharmacist, HospitalRoles.HospitalManager, HospitalRoles.SystemAdministrator]),
        new(HospitalPermissions.Pharmacy.PrescriptionView, "Pharmacy", "Reçete görüntüleme",
            [HospitalRoles.Doctor, HospitalRoles.Nurse, HospitalRoles.ChiefMedicalOfficer, HospitalRoles.Pharmacist, HospitalRoles.Patient]),
        new(HospitalPermissions.Pharmacy.PrescriptionCreate, "Pharmacy", "Reçete taslağı oluşturma",
            [HospitalRoles.Doctor, HospitalRoles.ChiefMedicalOfficer]),
        new(HospitalPermissions.Pharmacy.PrescriptionSign, "Pharmacy", "Reçete imzalama",
            [HospitalRoles.Doctor, HospitalRoles.ChiefMedicalOfficer]),
        new(HospitalPermissions.Pharmacy.PrescriptionCancel, "Pharmacy", "Reçete iptal etme",
            [HospitalRoles.Doctor, HospitalRoles.ChiefMedicalOfficer]),
        new(HospitalPermissions.Pharmacy.PrescriptionDispense, "Pharmacy", "Reçeteli ilaç teslimi",
            [HospitalRoles.Pharmacist]),
        new(HospitalPermissions.Pharmacy.InventoryPharmacyView, "Pharmacy", "Eczane ve sarf stoğunu görüntüleme",
            [HospitalRoles.Pharmacist, HospitalRoles.ChiefMedicalOfficer]),
        new(HospitalPermissions.Pharmacy.InventoryPharmacyAdjust, "Pharmacy", "Eczane stok hareketini yönetme",
            [HospitalRoles.Pharmacist]),

        // Diagnostics
        new(HospitalPermissions.Diagnostics.DiagnosticOrderCreate, "Diagnostics", "Tanısal istem verme",
            [HospitalRoles.Doctor, HospitalRoles.ChiefMedicalOfficer]),
        new(HospitalPermissions.Diagnostics.LaboratoryWorklistView, "Diagnostics", "Laboratuvar iş listesini görüntüleme",
            [HospitalRoles.LaboratoryStaff]),
        new(HospitalPermissions.Diagnostics.LaboratorySpecimenTransition, "Diagnostics", "Numune durum geçişi",
            [HospitalRoles.LaboratoryStaff]),
        new(HospitalPermissions.Diagnostics.LaboratoryResultEditDraft, "Diagnostics", "Taslak laboratuvar sonucu girme",
            [HospitalRoles.LaboratoryStaff]),
        new(HospitalPermissions.Diagnostics.LaboratoryResultFinalize, "Diagnostics", "Laboratuvar sonucunu kesinleştirme",
            [HospitalRoles.LaboratoryStaff]),
        new(HospitalPermissions.Diagnostics.RadiologyWorklistView, "Diagnostics", "Radyoloji iş listesini görüntüleme",
            [HospitalRoles.RadiologyStaff]),
        new(HospitalPermissions.Diagnostics.RadiologyStudyComplete, "Diagnostics", "Radyoloji çekimini tamamlama",
            [HospitalRoles.RadiologyStaff]),
        new(HospitalPermissions.Diagnostics.RadiologyReportFinalize, "Diagnostics", "Radyoloji raporunu kesinleştirme",
            [HospitalRoles.RadiologyStaff]),
        new(HospitalPermissions.Diagnostics.BloodTransfusionRecord, "Diagnostics", "Kan ürünü transfüzyon uygulamasını kaydetme",
            [HospitalRoles.Doctor, HospitalRoles.Nurse, HospitalRoles.ChiefMedicalOfficer]),
        new(HospitalPermissions.Diagnostics.DiagnosticResultViewFinalOwn, "Diagnostics", "Kendi kesinleşmiş sonuçlarını görüntüleme",
            [HospitalRoles.Patient]),

        // Inpatient & Critical Care
        new(HospitalPermissions.Inpatient.AdmissionRequest, "Inpatient", "Yatış istemi oluşturma",
            [HospitalRoles.Doctor, HospitalRoles.ChiefMedicalOfficer]),
        new(HospitalPermissions.Inpatient.AdmissionAccept, "Inpatient", "Yatış kabulünü onaylama",
            [HospitalRoles.Doctor, HospitalRoles.Nurse, HospitalRoles.ChiefMedicalOfficer, HospitalRoles.RegistrationStaff]),
        new(HospitalPermissions.Inpatient.BedAssign, "Inpatient", "Servis yatağı atama",
            [HospitalRoles.Nurse, HospitalRoles.ChiefMedicalOfficer, HospitalRoles.RegistrationStaff]),
        new(HospitalPermissions.Inpatient.BedTransfer, "Inpatient", "Servis yatak transferi yapma",
            [HospitalRoles.Nurse, HospitalRoles.ChiefMedicalOfficer]),
        new(HospitalPermissions.Inpatient.CarePlanManage, "Inpatient", "Bakım planını yönetme",
            [HospitalRoles.Nurse, HospitalRoles.ChiefMedicalOfficer]),
        new(HospitalPermissions.Inpatient.MedicationAdminister, "Inpatient", "İlaç uygulama (eMAR) kaydı girme",
            [HospitalRoles.Nurse, HospitalRoles.ChiefMedicalOfficer]),
        new(HospitalPermissions.Inpatient.DischargeComplete, "Inpatient", "Taburculuk işlemini tamamlama",
            [HospitalRoles.Doctor, HospitalRoles.ChiefMedicalOfficer]),
        new(HospitalPermissions.Inpatient.EmergencyTriageRecord, "Inpatient", "Acil triyaj kaydı oluşturma",
            [HospitalRoles.Nurse, HospitalRoles.Doctor, HospitalRoles.ChiefMedicalOfficer]),
        new(HospitalPermissions.Inpatient.SurgerySchedule, "Inpatient", "Ameliyat planlama",
            [HospitalRoles.Doctor, HospitalRoles.ChiefMedicalOfficer]),
        new(HospitalPermissions.Inpatient.CriticalCareRecord, "Inpatient", "Yoğun bakım takip kaydı girme",
            [HospitalRoles.Doctor, HospitalRoles.Nurse, HospitalRoles.ChiefMedicalOfficer]),

        // Specialty Care
        new(HospitalPermissions.SpecialtyCare.SpecialtyCareRecord, "SpecialtyCare", "Uzmanlık dikey süreçleri (gebelik, doğum, diş, evde sağlık) kaydı girme",
            [HospitalRoles.Doctor, HospitalRoles.Nurse, HospitalRoles.ChiefMedicalOfficer]),
        new(HospitalPermissions.SpecialtyCare.SpecialtyCareManage, "SpecialtyCare", "Uzmanlık bakım planı ve sevk yönetimi",
            [HospitalRoles.Doctor, HospitalRoles.ChiefMedicalOfficer]),
        new(HospitalPermissions.SpecialtyCare.SpecialtyCareView, "SpecialtyCare", "Uzmanlık kayıtlarını görüntüleme",
            [HospitalRoles.Doctor, HospitalRoles.Nurse, HospitalRoles.ChiefMedicalOfficer]),
        new(HospitalPermissions.SpecialtyCare.SpecialtyCareViewOwn, "SpecialtyCare", "Hasta portalında kendi yayınlanmış uzmanlık kayıt özetlerini görüntüleme",
            [HospitalRoles.Patient]),

        // Interoperability
        new(HospitalPermissions.Interoperability.MockManage, "Interoperability", "MOCK entegrasyon yapılandırmasını ve teknik günlüklerini yönetme",
            [HospitalRoles.SystemAdministrator]),
        new(HospitalPermissions.Interoperability.ClinicalExchange, "Interoperability", "Hasta kapsamı doğrulanmış klinik MOCK veri alışverişini yürütme",
            [HospitalRoles.Doctor, HospitalRoles.ChiefMedicalOfficer]),
        new(HospitalPermissions.Interoperability.FhirExport, "Interoperability", "Hasta düzeyinde FHIR R4 export paketi oluşturma",
            [HospitalRoles.ChiefMedicalOfficer]),

        // Reporting & Audit
        new(HospitalPermissions.ReportingAndAudit.ProjectionManage, "ReportingAndAudit", "Raporlama projeksiyonlarını yeniden kurma ve teknik durumunu görüntüleme",
            [HospitalRoles.SystemAdministrator]),
        new(HospitalPermissions.ReportingAndAudit.ReportOperationsView, "ReportingAndAudit", "Operasyonel raporları görüntüleme",
            [HospitalRoles.Doctor, HospitalRoles.Nurse, HospitalRoles.ChiefMedicalOfficer, HospitalRoles.RegistrationStaff, HospitalRoles.LaboratoryStaff, HospitalRoles.RadiologyStaff, HospitalRoles.Pharmacist, HospitalRoles.HospitalManager]),
        new(HospitalPermissions.ReportingAndAudit.ReportOperationsExport, "ReportingAndAudit", "Operasyonel raporları dışa aktarma",
            [HospitalRoles.ChiefMedicalOfficer, HospitalRoles.HospitalManager]),
        new(HospitalPermissions.ReportingAndAudit.AuditTechnicalView, "ReportingAndAudit", "Teknik audit kayıtlarını görüntüleme",
            [HospitalRoles.SystemAdministrator]),
        new(HospitalPermissions.ReportingAndAudit.AuditClinicalAccessView, "ReportingAndAudit", "Klinik erişim audit kayıtlarını görüntüleme",
            [HospitalRoles.ChiefMedicalOfficer]),
        new(HospitalPermissions.ReportingAndAudit.AuditOwnAccessView, "ReportingAndAudit", "Kendi erişim audit özetini görüntüleme",
            [HospitalRoles.Patient]),
    ];

    private static readonly HashSet<string> PermissionNameSet = new(
        All.Select(p => p.Name),
        StringComparer.Ordinal);

    public static bool IsKnown(string permission) =>
        !string.IsNullOrWhiteSpace(permission) && PermissionNameSet.Contains(permission.Trim());
}
