// <auto-generated />
using System;
using HospitalManagement.Modules.Pharmacy.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HospitalManagement.Modules.Pharmacy.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PharmacyDbContext))]
    [Migration("20260829165343_HardenPhase5AuthorizationConcurrency")]
    partial class HardenPhase5AuthorizationConcurrency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("pharmacy")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HospitalManagement.Modules.Pharmacy.Domain.MedicationCatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AtcCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("atc_code");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("brand_name");

                    b.Property<string>("CatalogVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("catalog_version");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("form");

                    b.Property<string>("GenericName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("generic_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("route");

                    b.Property<string>("StrengthUnit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("strength_unit");

                    b.Property<decimal>("StrengthValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("strength_value");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("AtcCode")
                        .HasDatabaseName("ix_medication_catalog_items_atc_code");

                    b.HasIndex("BrandName")
                        .HasDatabaseName("ix_medication_catalog_items_brand_name");

                    b.HasIndex("CatalogVersion")
                        .HasDatabaseName("ix_medication_catalog_items_catalog_version");

                    b.HasIndex("GenericName")
                        .HasDatabaseName("ix_medication_catalog_items_generic_name");

                    b.HasIndex("Code", "CatalogVersion")
                        .IsUnique()
                        .HasDatabaseName("ux_medication_catalog_items_code_version");

                    b.ToTable("medication_catalog_items", "pharmacy");
                });

            modelBuilder.Entity("HospitalManagement.Modules.Pharmacy.Domain.MedicationStockItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<DateTime>("ExpirationDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_date_utc");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("location");

                    b.Property<string>("LotNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("lot_number");

                    b.Property<Guid>("MedicationCatalogItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("medication_catalog_item_id");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_on_hand");

                    b.Property<int>("QuantityReserved")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_reserved");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("integer")
                        .HasColumnName("reorder_level");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_medication_stock_items_department_id");

                    b.HasIndex("MedicationCatalogItemId", "ExpirationDateUtc")
                        .HasDatabaseName("ix_medication_stock_items_fefo");

                    b.HasIndex("DepartmentId", "MedicationCatalogItemId", "Location", "LotNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_medication_stock_items_catalog_location_lot");

                    b.ToTable("medication_stock_items", "pharmacy", t =>
                        {
                            t.HasCheckConstraint("ck_medication_stock_items_quantity_on_hand", "quantity_on_hand >= 0");

                            t.HasCheckConstraint("ck_medication_stock_items_quantity_reserved", "quantity_reserved >= 0");

                            t.HasCheckConstraint("ck_medication_stock_items_reorder_level", "reorder_level >= 0");

                            t.HasCheckConstraint("ck_medication_stock_items_reserved_not_above_on_hand", "quantity_reserved <= quantity_on_hand");
                        });
                });

            modelBuilder.Entity("HospitalManagement.Modules.Pharmacy.Domain.MedicationStockTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("NewQuantityOnHand")
                        .HasColumnType("integer")
                        .HasColumnName("new_quantity_on_hand");

                    b.Property<string>("Notes")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("PerformedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at_utc");

                    b.Property<Guid?>("PerformedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("performed_by_user_id");

                    b.Property<int>("PreviousQuantityOnHand")
                        .HasColumnType("integer")
                        .HasColumnName("previous_quantity_on_hand");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reference_id");

                    b.Property<Guid>("StockItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("stock_item_id");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("transaction_type");

                    b.HasKey("Id");

                    b.HasIndex("PerformedAtUtc")
                        .HasDatabaseName("ix_medication_stock_transactions_performed_at");

                    b.HasIndex("StockItemId")
                        .HasDatabaseName("ix_medication_stock_transactions_stock_item_id");

                    b.ToTable("medication_stock_transactions", "pharmacy");
                });

            modelBuilder.Entity("HospitalManagement.Modules.Pharmacy.Domain.Prescription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<Guid?>("CancelledByDoctorId")
                        .HasColumnType("uuid")
                        .HasColumnName("cancelled_by_doctor_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("DiagnosisSummary")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("diagnosis_summary");

                    b.Property<Guid>("EncounterId")
                        .HasColumnType("uuid")
                        .HasColumnName("encounter_id");

                    b.Property<DateTime?>("EnteredInErrorAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entered_in_error_at_utc");

                    b.Property<Guid?>("EnteredInErrorByDoctorId")
                        .HasColumnType("uuid")
                        .HasColumnName("entered_in_error_by_doctor_id");

                    b.Property<string>("EnteredInErrorReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("entered_in_error_reason");

                    b.Property<string>("GeneralInstructions")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("general_instructions");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<Guid>("PrescribingDoctorId")
                        .HasColumnType("uuid")
                        .HasColumnName("prescribing_doctor_id");

                    b.Property<string>("PrescriptionNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("prescription_number");

                    b.Property<DateTime?>("SignedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("signed_at_utc");

                    b.Property<Guid?>("SignedByDoctorId")
                        .HasColumnType("uuid")
                        .HasColumnName("signed_by_doctor_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<DateTime?>("ValidUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until_utc");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("EncounterId")
                        .HasDatabaseName("ix_prescriptions_encounter_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_prescriptions_patient_id");

                    b.HasIndex("PrescribingDoctorId")
                        .HasDatabaseName("ix_prescriptions_prescribing_doctor_id");

                    b.HasIndex("PrescriptionNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_prescriptions_prescription_number");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_prescriptions_status");

                    b.ToTable("prescriptions", "pharmacy");
                });

            modelBuilder.Entity("HospitalManagement.Modules.Pharmacy.Domain.PrescriptionDispenseOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("PrescriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("prescription_id");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_fingerprint");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_prescription_dispense_operations_idempotency_key");

                    b.HasIndex("PrescriptionId")
                        .HasDatabaseName("ix_prescription_dispense_operations_prescription_id");

                    b.ToTable("prescription_dispense_operations", "pharmacy");
                });

            modelBuilder.Entity("HospitalManagement.Modules.Pharmacy.Domain.PrescriptionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("brand_name");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("DispensedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("dispensed_quantity");

                    b.Property<decimal>("Dose")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("dose");

                    b.Property<string>("DoseUnit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("dose_unit");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer")
                        .HasColumnName("duration_days");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("form");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("frequency");

                    b.Property<string>("GenericName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("generic_name");

                    b.Property<string>("Instructions")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("instructions");

                    b.Property<Guid>("MedicationCatalogItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("medication_catalog_item_id");

                    b.Property<string>("MedicationCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("medication_code");

                    b.Property<Guid>("PrescriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("prescription_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("QuantityUnit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("quantity_unit");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("route");

                    b.HasKey("Id");

                    b.HasIndex("MedicationCatalogItemId")
                        .HasDatabaseName("ix_prescription_items_medication_catalog_item_id");

                    b.HasIndex("PrescriptionId")
                        .HasDatabaseName("ix_prescription_items_prescription_id");

                    b.ToTable("prescription_items", "pharmacy");
                });

            modelBuilder.Entity("HospitalManagement.Modules.Pharmacy.Domain.PrescriptionItem", b =>
                {
                    b.HasOne("HospitalManagement.Modules.Pharmacy.Domain.Prescription", null)
                        .WithMany("Items")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HospitalManagement.Modules.Pharmacy.Domain.Prescription", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
