// <auto-generated />
using System;
using HospitalManagement.Modules.Pharmacy.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HospitalManagement.Modules.Pharmacy.Infrastructure.Persistence.Migrations;

[DbContext(typeof(PharmacyDbContext))]
[Migration("20260829020000_AddPrescriptions")]
partial class AddPrescriptions
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("pharmacy")
            .HasAnnotation("ProductVersion", "9.0.2")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("HospitalManagement.Modules.Pharmacy.Domain.MedicationCatalogItem", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("AtcCode")
                    .HasMaxLength(16)
                    .HasColumnType("character varying(16)")
                    .HasColumnName("atc_code");

                b.Property<string>("BrandName")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("brand_name");

                b.Property<string>("CatalogVersion")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("catalog_version");

                b.Property<string>("Code")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("code");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at_utc");

                b.Property<string>("Description")
                    .HasMaxLength(1024)
                    .HasColumnType("character varying(1024)")
                    .HasColumnName("description");

                b.Property<string>("Form")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("form");

                b.Property<string>("GenericName")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("generic_name");

                b.Property<bool>("IsActive")
                    .HasColumnType("boolean")
                    .HasColumnName("is_active");

                b.Property<string>("Route")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("route");

                b.Property<string>("StrengthUnit")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("strength_unit");

                b.Property<decimal>("StrengthValue")
                    .HasPrecision(18, 4)
                    .HasColumnType("numeric(18,4)")
                    .HasColumnName("strength_value");

                b.Property<DateTime?>("UpdatedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("updated_at_utc");

                b.HasKey("Id");

                b.HasIndex("AtcCode")
                    .HasDatabaseName("ix_medication_catalog_items_atc_code");

                b.HasIndex("BrandName")
                    .HasDatabaseName("ix_medication_catalog_items_brand_name");

                b.HasIndex("CatalogVersion")
                    .HasDatabaseName("ix_medication_catalog_items_catalog_version");

                b.HasIndex("GenericName")
                    .HasDatabaseName("ix_medication_catalog_items_generic_name");

                b.HasIndex("Code", "CatalogVersion")
                    .IsUnique()
                    .HasDatabaseName("ux_medication_catalog_items_code_version");

                b.ToTable("medication_catalog_items", "pharmacy");
            });

        modelBuilder.Entity("HospitalManagement.Modules.Pharmacy.Domain.Prescription", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTime?>("CancelledAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("cancelled_at_utc");

                b.Property<Guid?>("CancelledByDoctorId")
                    .HasColumnType("uuid")
                    .HasColumnName("cancelled_by_doctor_id");

                b.Property<string>("CancellationReason")
                    .HasMaxLength(512)
                    .HasColumnType("character varying(512)")
                    .HasColumnName("cancellation_reason");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at_utc");

                b.Property<Guid>("DepartmentId")
                    .HasColumnType("uuid")
                    .HasColumnName("department_id");

                b.Property<string>("DiagnosisSummary")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("diagnosis_summary");

                b.Property<Guid>("EncounterId")
                    .HasColumnType("uuid")
                    .HasColumnName("encounter_id");

                b.Property<DateTime?>("EnteredInErrorAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("entered_in_error_at_utc");

                b.Property<Guid?>("EnteredInErrorByDoctorId")
                    .HasColumnType("uuid")
                    .HasColumnName("entered_in_error_by_doctor_id");

                b.Property<string>("EnteredInErrorReason")
                    .HasMaxLength(512)
                    .HasColumnType("character varying(512)")
                    .HasColumnName("entered_in_error_reason");

                b.Property<string>("GeneralInstructions")
                    .HasMaxLength(1024)
                    .HasColumnType("character varying(1024)")
                    .HasColumnName("general_instructions");

                b.Property<Guid>("PatientId")
                    .HasColumnType("uuid")
                    .HasColumnName("patient_id");

                b.Property<Guid>("PrescribingDoctorId")
                    .HasColumnType("uuid")
                    .HasColumnName("prescribing_doctor_id");

                b.Property<string>("PrescriptionNumber")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("prescription_number");

                b.Property<DateTime?>("SignedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("signed_at_utc");

                b.Property<Guid?>("SignedByDoctorId")
                    .HasColumnType("uuid")
                    .HasColumnName("signed_by_doctor_id");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("status");

                b.Property<DateTime?>("UpdatedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("updated_at_utc");

                b.Property<DateTime?>("ValidUntilUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("valid_until_utc");

                b.Property<int>("Version")
                    .HasColumnType("integer")
                    .HasColumnName("version");

                b.HasKey("Id");

                b.HasIndex("EncounterId")
                    .HasDatabaseName("ix_prescriptions_encounter_id");

                b.HasIndex("PatientId")
                    .HasDatabaseName("ix_prescriptions_patient_id");

                b.HasIndex("PrescribingDoctorId")
                    .HasDatabaseName("ix_prescriptions_prescribing_doctor_id");

                b.HasIndex("PrescriptionNumber")
                    .IsUnique()
                    .HasDatabaseName("ux_prescriptions_prescription_number");

                b.HasIndex("Status")
                    .HasDatabaseName("ix_prescriptions_status");

                b.ToTable("prescriptions", "pharmacy");
            });

        modelBuilder.Entity("HospitalManagement.Modules.Pharmacy.Domain.PrescriptionItem", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("BrandName")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("brand_name");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at_utc");

                b.Property<int>("DispensedQuantity")
                    .HasColumnType("integer")
                    .HasColumnName("dispensed_quantity");

                b.Property<decimal>("Dose")
                    .HasPrecision(18, 4)
                    .HasColumnType("numeric(18,4)")
                    .HasColumnName("dose");

                b.Property<string>("DoseUnit")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("dose_unit");

                b.Property<int>("DurationDays")
                    .HasColumnType("integer")
                    .HasColumnName("duration_days");

                b.Property<string>("Form")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("form");

                b.Property<string>("Frequency")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("frequency");

                b.Property<string>("GenericName")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("generic_name");

                b.Property<string>("Instructions")
                    .HasMaxLength(512)
                    .HasColumnType("character varying(512)")
                    .HasColumnName("instructions");

                b.Property<Guid>("MedicationCatalogItemId")
                    .HasColumnType("uuid")
                    .HasColumnName("medication_catalog_item_id");

                b.Property<string>("MedicationCode")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("medication_code");

                b.Property<Guid>("PrescriptionId")
                    .HasColumnType("uuid")
                    .HasColumnName("prescription_id");

                b.Property<int>("Quantity")
                    .HasColumnType("integer")
                    .HasColumnName("quantity");

                b.Property<string>("QuantityUnit")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("quantity_unit");

                b.Property<string>("Route")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("route");

                b.HasKey("Id");

                b.HasIndex("MedicationCatalogItemId")
                    .HasDatabaseName("ix_prescription_items_medication_catalog_item_id");

                b.HasIndex("PrescriptionId")
                    .HasDatabaseName("ix_prescription_items_prescription_id");

                b.ToTable("prescription_items", "pharmacy");
            });

        modelBuilder.Entity("HospitalManagement.Modules.Pharmacy.Domain.PrescriptionItem", b =>
            {
                b.HasOne("HospitalManagement.Modules.Pharmacy.Domain.Prescription", null)
                    .WithMany("Items")
                    .HasForeignKey("PrescriptionId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("HospitalManagement.Modules.Pharmacy.Domain.Prescription", b =>
            {
                b.Navigation("Items");
            });
#pragma warning restore 612, 618
    }
}
