// <auto-generated />
using System;
using HospitalManagement.Modules.Emergency.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HospitalManagement.Modules.Emergency.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EmergencyDbContext))]
    [Migration("20260831000100_InitialEmergencySchema")]
    partial class InitialEmergencySchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("emergency")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HospitalManagement.Modules.Emergency.Domain.EmergencyAdmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdmissionNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("AdmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AdmittingStaffId")
                        .HasColumnType("uuid");

                    b.Property<string>("ArrivalType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("AssignedBedOrZone")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("AssignedDoctorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChiefComplaint")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DischargeOrDispositionNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("EmergencyProtocolNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsRowVersion()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("EmergencyProtocolNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("PatientId", "Status");

                    b.ToTable("EmergencyAdmissions", "emergency");
                });

            modelBuilder.Entity("HospitalManagement.Modules.Emergency.Domain.EmergencyAdmission", b =>
                {
                    b.OwnsOne("HospitalManagement.Modules.Emergency.Domain.EmergencyTriageInfo", "Triage", b1 =>
                        {
                            b1.Property<Guid>("EmergencyAdmissionId")
                                .HasColumnType("uuid");

                            b1.Property<decimal?>("BodyTemperatureCelsius")
                                .HasPrecision(4, 1)
                                .HasColumnType("numeric(4,1)")
                                .HasColumnName("BodyTemperatureCelsius");

                            b1.Property<string>("ClinicalNotes")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("TriageClinicalNotes");

                            b1.Property<string>("Consciousness")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("Consciousness");

                            b1.Property<int?>("DiastolicBp")
                                .HasColumnType("integer")
                                .HasColumnName("DiastolicBp");

                            b1.Property<bool>("EducationalClassificationAssisted")
                                .HasColumnType("boolean")
                                .HasColumnName("EducationalClassificationAssisted");

                            b1.Property<int?>("HeartRate")
                                .HasColumnType("integer")
                                .HasColumnName("HeartRate");

                            b1.Property<int?>("OxygenSaturationPercent")
                                .HasColumnType("integer")
                                .HasColumnName("OxygenSaturationPercent");

                            b1.Property<int?>("PainScale")
                                .HasColumnType("integer")
                                .HasColumnName("PainScale");

                            b1.Property<int?>("RespiratoryRate")
                                .HasColumnType("integer")
                                .HasColumnName("RespiratoryRate");

                            b1.Property<int?>("SystolicBp")
                                .HasColumnType("integer")
                                .HasColumnName("SystolicBp");

                            b1.Property<string>("TriageCategoryReason")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("TriageCategoryReason");

                            b1.Property<string>("TriageLevel")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("TriageLevel");

                            b1.Property<Guid>("TriageNurseId")
                                .HasColumnType("uuid")
                                .HasColumnName("TriageNurseId");

                            b1.Property<DateTime>("TriagedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("TriagedAtUtc");

                            b1.HasKey("EmergencyAdmissionId");

                            b1.ToTable("EmergencyAdmissions", "emergency");

                            b1.WithOwner()
                                .HasForeignKey("EmergencyAdmissionId");
                        });

                    b.Navigation("Triage");
                });
#pragma warning restore 612, 618
        }
    }
}
