// <auto-generated />
using System;
using HospitalManagement.Modules.Emergency.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HospitalManagement.Modules.Emergency.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EmergencyDbContext))]
    partial class EmergencyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("emergency")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HospitalManagement.Modules.Emergency.Domain.EmergencyAdmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdmissionNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("AdmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AdmittingStaffId")
                        .HasColumnType("uuid");

                    b.Property<string>("ArrivalType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("AssignedBedOrZone")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("AssignedDoctorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChiefComplaint")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DischargeOrDispositionNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("EmergencyProtocolNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsRowVersion()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("EmergencyProtocolNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("PatientId", "Status");

                    b.ToTable("EmergencyAdmissions", "emergency");
                });

            modelBuilder.Entity("HospitalManagement.Modules.Emergency.Domain.EmergencyAdmission", b =>
                {
                    b.OwnsOne("HospitalManagement.Modules.Emergency.Domain.EmergencyDispositionInfo", "Disposition", b1 =>
                        {
                            b1.Property<Guid>("EmergencyAdmissionId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("DecidedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("DispositionDecidedAtUtc");

                            b1.Property<Guid>("DecidedByDoctorId")
                                .HasColumnType("uuid")
                                .HasColumnName("DispositionDecidedByDoctorId");

                            b1.Property<string>("DispositionSummaryNotes")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("DispositionSummaryNotes");

                            b1.Property<string>("DispositionType")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("DispositionType");

                            b1.Property<string>("FollowUpInstructions")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("DispositionFollowUpInstructions");

                            b1.Property<string>("TargetDepartmentName")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("DispositionTargetDepartmentName");

                            b1.Property<Guid?>("TargetWardOrIcuId")
                                .HasColumnType("uuid")
                                .HasColumnName("DispositionTargetWardOrIcuId");

                            b1.HasKey("EmergencyAdmissionId");

                            b1.ToTable("EmergencyAdmissions", "emergency");

                            b1.WithOwner()
                                .HasForeignKey("EmergencyAdmissionId");
                        });

                    b.OwnsOne("HospitalManagement.Modules.Emergency.Domain.EmergencyTriageInfo", "Triage", b1 =>
                        {
                            b1.Property<Guid>("EmergencyAdmissionId")
                                .HasColumnType("uuid");

                            b1.Property<decimal?>("BodyTemperatureCelsius")
                                .HasPrecision(4, 1)
                                .HasColumnType("numeric(4,1)")
                                .HasColumnName("BodyTemperatureCelsius");

                            b1.Property<string>("ClinicalNotes")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("TriageClinicalNotes");

                            b1.Property<string>("Consciousness")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("Consciousness");

                            b1.Property<int?>("DiastolicBp")
                                .HasColumnType("integer")
                                .HasColumnName("DiastolicBp");

                            b1.Property<bool>("EducationalClassificationAssisted")
                                .HasColumnType("boolean")
                                .HasColumnName("EducationalClassificationAssisted");

                            b1.Property<int?>("HeartRate")
                                .HasColumnType("integer")
                                .HasColumnName("HeartRate");

                            b1.Property<int?>("OxygenSaturationPercent")
                                .HasColumnType("integer")
                                .HasColumnName("OxygenSaturationPercent");

                            b1.Property<int?>("PainScale")
                                .HasColumnType("integer")
                                .HasColumnName("PainScale");

                            b1.Property<int?>("RespiratoryRate")
                                .HasColumnType("integer")
                                .HasColumnName("RespiratoryRate");

                            b1.Property<int?>("SystolicBp")
                                .HasColumnType("integer")
                                .HasColumnName("SystolicBp");

                            b1.Property<string>("TriageCategoryReason")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("TriageCategoryReason");

                            b1.Property<string>("TriageLevel")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("TriageLevel");

                            b1.Property<Guid>("TriageNurseId")
                                .HasColumnType("uuid")
                                .HasColumnName("TriageNurseId");

                            b1.Property<DateTime>("TriagedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("TriagedAtUtc");

                            b1.HasKey("EmergencyAdmissionId");

                            b1.ToTable("EmergencyAdmissions", "emergency");

                            b1.WithOwner()
                                .HasForeignKey("EmergencyAdmissionId");
                        });

                    b.Navigation("Disposition");

                    b.Navigation("Triage");
                });

            modelBuilder.Entity("HospitalManagement.Modules.Emergency.Domain.EmergencyCareOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdmissionId")
                        .HasColumnType("uuid");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ClinicalInstructions")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderCatalogCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("OrderCatalogName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("OrderedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderedByDoctorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ResultSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<uint>("Version")
                        .IsRowVersion()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("OrderedAtUtc");

                    b.HasIndex("AdmissionId", "Status");

                    b.ToTable("EmergencyCareOrders", "emergency");
                });

            modelBuilder.Entity("HospitalManagement.Modules.Emergency.Domain.EmergencyConsultation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdmissionId")
                        .HasColumnType("uuid");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ClinicalReason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("ConsultantDoctorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConsultationResponseNotes")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequestedByDoctorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RespondedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Urgency")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<uint>("Version")
                        .IsRowVersion()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("RequestedAtUtc");

                    b.HasIndex("AdmissionId", "Status");

                    b.HasIndex("DepartmentId", "Status");

                    b.ToTable("EmergencyConsultations", "emergency");
                });
#pragma warning restore 612, 618
        }
    }
}
