// <auto-generated />
using System;
using HospitalManagement.Modules.ClinicalRecords.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HospitalManagement.Modules.ClinicalRecords.Infrastructure.Persistence.Migrations;

[DbContext(typeof(ClinicalRecordsDbContext))]
[Migration("20260828020000_AddVitalSigns")]
partial class AddVitalSigns
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("clinical_records")
            .HasAnnotation("ProductVersion", "10.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("HospitalManagement.Modules.ClinicalRecords.Domain.AllergyIntolerance", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<int>("Category")
                    .HasColumnType("integer")
                    .HasColumnName("category");

                b.Property<int>("ClinicalStatus")
                    .HasColumnType("integer")
                    .HasColumnName("clinical_status");

                b.Property<int>("Criticality")
                    .HasColumnType("integer")
                    .HasColumnName("criticality");

                b.Property<Guid?>("EncounterId")
                    .HasColumnType("uuid")
                    .HasColumnName("encounter_id");

                b.Property<string>("EnteredInErrorReason")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("entered_in_error_reason");

                b.Property<string>("Manifestation")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("manifestation");

                b.Property<string>("Notes")
                    .HasMaxLength(1000)
                    .HasColumnType("character varying(1000)")
                    .HasColumnName("notes");

                b.Property<DateTime?>("OnsetDateTimeUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("onset_date_time_utc");

                b.Property<Guid>("PatientId")
                    .HasColumnType("uuid")
                    .HasColumnName("patient_id");

                b.Property<DateTime>("RecordedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("recorded_at_utc");

                b.Property<Guid>("RecordedByPractitionerId")
                    .HasColumnType("uuid")
                    .HasColumnName("recorded_by_practitioner_id");

                b.Property<string>("Substance")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("substance");

                b.Property<DateTime?>("UpdatedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("updated_at_utc");

                b.Property<int>("VerificationStatus")
                    .HasColumnType("integer")
                    .HasColumnName("verification_status");

                b.Property<long>("Version")
                    .IsConcurrencyToken()
                    .HasColumnType("bigint")
                    .HasColumnName("version");

                b.HasKey("Id");

                b.HasIndex("ClinicalStatus")
                    .HasDatabaseName("ix_allergy_intolerances_clinical_status");

                b.HasIndex("PatientId")
                    .HasDatabaseName("ix_allergy_intolerances_patient_id");

                b.ToTable("allergy_intolerances", "clinical_records");
            });

        modelBuilder.Entity("HospitalManagement.Modules.ClinicalRecords.Domain.ClinicalProblem", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<int>("Category")
                    .HasColumnType("integer")
                    .HasColumnName("category");

                b.Property<int>("ClinicalStatus")
                    .HasColumnType("integer")
                    .HasColumnName("clinical_status");

                b.Property<string>("Code")
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("code");

                b.Property<Guid?>("EncounterId")
                    .HasColumnType("uuid")
                    .HasColumnName("encounter_id");

                b.Property<string>("EnteredInErrorReason")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("entered_in_error_reason");

                b.Property<string>("Notes")
                    .HasMaxLength(1000)
                    .HasColumnType("character varying(1000)")
                    .HasColumnName("notes");

                b.Property<DateOnly?>("OnsetDate")
                    .HasColumnType("date")
                    .HasColumnName("onset_date");

                b.Property<Guid>("PatientId")
                    .HasColumnType("uuid")
                    .HasColumnName("patient_id");

                b.Property<string>("ProblemTitle")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("problem_title");

                b.Property<DateTime>("RecordedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("recorded_at_utc");

                b.Property<Guid>("RecordedByPractitionerId")
                    .HasColumnType("uuid")
                    .HasColumnName("recorded_by_practitioner_id");

                b.Property<DateOnly?>("ResolvedDate")
                    .HasColumnType("date")
                    .HasColumnName("resolved_date");

                b.Property<DateTime?>("UpdatedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("updated_at_utc");

                b.Property<int>("VerificationStatus")
                    .HasColumnType("integer")
                    .HasColumnName("verification_status");

                b.Property<long>("Version")
                    .IsConcurrencyToken()
                    .HasColumnType("bigint")
                    .HasColumnName("version");

                b.HasKey("Id");

                b.HasIndex("Category")
                    .HasDatabaseName("ix_clinical_problems_category");

                b.HasIndex("ClinicalStatus")
                    .HasDatabaseName("ix_clinical_problems_clinical_status");

                b.HasIndex("PatientId")
                    .HasDatabaseName("ix_clinical_problems_patient_id");

                b.ToTable("clinical_problems", "clinical_records");
            });

        modelBuilder.Entity("HospitalManagement.Modules.ClinicalRecords.Domain.Encounter", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTime?>("ActualEndTimeUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("actual_end_time_utc");

                b.Property<DateTime?>("ActualStartTimeUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("actual_start_time_utc");

                b.Property<Guid?>("AppointmentId")
                    .HasColumnType("uuid")
                    .HasColumnName("appointment_id");

                b.Property<string>("CancellationReason")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("cancellation_reason");

                b.Property<string>("ChiefComplaint")
                    .HasMaxLength(1000)
                    .HasColumnType("character varying(1000)")
                    .HasColumnName("chief_complaint");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at_utc");

                b.Property<Guid>("DepartmentId")
                    .HasColumnType("uuid")
                    .HasColumnName("department_id");

                b.Property<int>("EncounterType")
                    .HasColumnType("integer")
                    .HasColumnName("encounter_type");

                b.Property<string>("EnteredInErrorReason")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("entered_in_error_reason");

                b.Property<Guid>("PatientId")
                    .HasColumnType("uuid")
                    .HasColumnName("patient_id");

                b.Property<DateTime?>("PlannedStartTimeUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("planned_start_time_utc");

                b.Property<Guid>("PrimaryPractitionerId")
                    .HasColumnType("uuid")
                    .HasColumnName("primary_practitioner_id");

                b.Property<int>("Status")
                    .HasColumnType("integer")
                    .HasColumnName("status");

                b.Property<DateTime?>("UpdatedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("updated_at_utc");

                b.Property<long>("Version")
                    .IsConcurrencyToken()
                    .HasColumnType("bigint")
                    .HasColumnName("version");

                b.HasKey("Id");

                b.HasIndex("AppointmentId")
                    .IsUnique()
                    .HasDatabaseName("ux_encounters_appointment_active")
                    .HasFilter("\"appointment_id\" IS NOT NULL AND \"status\" IN (1, 2, 3)");

                b.HasIndex("DepartmentId")
                    .HasDatabaseName("ix_encounters_department_id");

                b.HasIndex("PatientId")
                    .HasDatabaseName("ix_encounters_patient_id");

                b.HasIndex("PrimaryPractitionerId")
                    .HasDatabaseName("ix_encounters_primary_practitioner_id");

                b.HasIndex("Status")
                    .HasDatabaseName("ix_encounters_status");

                b.ToTable("encounters", "clinical_records");
            });

        modelBuilder.Entity("HospitalManagement.Modules.ClinicalRecords.Domain.EncounterParticipant", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at_utc");

                b.Property<Guid>("EncounterId")
                    .HasColumnType("uuid")
                    .HasColumnName("encounter_id");

                b.Property<DateTime>("JoinedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("joined_at_utc");

                b.Property<DateTime?>("LeftAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("left_at_utc");

                b.Property<Guid>("PractitionerId")
                    .HasColumnType("uuid")
                    .HasColumnName("practitioner_id");

                b.Property<int>("Role")
                    .HasColumnType("integer")
                    .HasColumnName("role");

                b.HasKey("Id");

                b.HasIndex("EncounterId")
                    .HasDatabaseName("ix_encounter_participants_encounter_id");

                b.HasIndex("PractitionerId")
                    .HasDatabaseName("ix_encounter_participants_practitioner_id");

                b.ToTable("encounter_participants", "clinical_records");
            });

        modelBuilder.Entity("HospitalManagement.Modules.ClinicalRecords.Domain.VitalSignObservation", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<Guid?>("EncounterId")
                    .HasColumnType("uuid")
                    .HasColumnName("encounter_id");

                b.Property<string>("EnteredInErrorReason")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("entered_in_error_reason");

                b.Property<int>("Interpretation")
                    .HasColumnType("integer")
                    .HasColumnName("interpretation");

                b.Property<bool>("IsEnteredInError")
                    .HasColumnType("boolean")
                    .HasColumnName("is_entered_in_error");

                b.Property<DateTime>("MeasuredAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("measured_at_utc");

                b.Property<string>("MeasurementMethod")
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)")
                    .HasColumnName("measurement_method");

                b.Property<int>("MeasurementType")
                    .HasColumnType("integer")
                    .HasColumnName("measurement_type");

                b.Property<string>("Notes")
                    .HasMaxLength(1000)
                    .HasColumnType("character varying(1000)")
                    .HasColumnName("notes");

                b.Property<Guid>("PatientId")
                    .HasColumnType("uuid")
                    .HasColumnName("patient_id");

                b.Property<DateTime>("RecordedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("recorded_at_utc");

                b.Property<Guid>("RecordedByPractitionerId")
                    .HasColumnType("uuid")
                    .HasColumnName("recorded_by_practitioner_id");

                b.Property<string>("Unit")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("unit");

                b.Property<DateTime?>("UpdatedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("updated_at_utc");

                b.Property<decimal>("Value")
                    .HasPrecision(10, 2)
                    .HasColumnType("numeric(10,2)")
                    .HasColumnName("value");

                b.Property<long>("Version")
                    .IsConcurrencyToken()
                    .HasColumnType("bigint")
                    .HasColumnName("version");

                b.HasKey("Id");

                b.HasIndex("EncounterId")
                    .HasDatabaseName("ix_vital_sign_observations_encounter_id");

                b.HasIndex("MeasuredAtUtc")
                    .HasDatabaseName("ix_vital_sign_observations_measured_at_utc");

                b.HasIndex("PatientId")
                    .HasDatabaseName("ix_vital_sign_observations_patient_id");

                b.ToTable("vital_sign_observations", "clinical_records");
            });

        modelBuilder.Entity("HospitalManagement.Modules.ClinicalRecords.Domain.EncounterParticipant", b =>
            {
                b.HasOne("HospitalManagement.Modules.ClinicalRecords.Domain.Encounter", null)
                    .WithMany("Participants")
                    .HasForeignKey("EncounterId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("HospitalManagement.Modules.ClinicalRecords.Domain.Encounter", b =>
            {
                b.Navigation("Participants");
            });
#pragma warning restore 612, 618
    }
}
