// <auto-generated />
using System;
using HospitalManagement.Modules.ClinicalRecords.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HospitalManagement.Modules.ClinicalRecords.Infrastructure.Persistence.Migrations;

[DbContext(typeof(ClinicalRecordsDbContext))]
[Migration("20260828004000_InitialClinicalRecords")]
partial class InitialClinicalRecords
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("clinical_records")
            .HasAnnotation("ProductVersion", "10.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("HospitalManagement.Modules.ClinicalRecords.Domain.Encounter", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTime?>("ActualEndTimeUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("actual_end_time_utc");

                b.Property<DateTime?>("ActualStartTimeUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("actual_start_time_utc");

                b.Property<Guid?>("AppointmentId")
                    .HasColumnType("uuid")
                    .HasColumnName("appointment_id");

                b.Property<string>("CancellationReason")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("cancellation_reason");

                b.Property<string>("ChiefComplaint")
                    .HasMaxLength(1000)
                    .HasColumnType("character varying(1000)")
                    .HasColumnName("chief_complaint");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at_utc");

                b.Property<Guid>("DepartmentId")
                    .HasColumnType("uuid")
                    .HasColumnName("department_id");

                b.Property<int>("EncounterType")
                    .HasColumnType("integer")
                    .HasColumnName("encounter_type");

                b.Property<string>("EnteredInErrorReason")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("entered_in_error_reason");

                b.Property<Guid>("PatientId")
                    .HasColumnType("uuid")
                    .HasColumnName("patient_id");

                b.Property<DateTime?>("PlannedStartTimeUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("planned_start_time_utc");

                b.Property<Guid>("PrimaryPractitionerId")
                    .HasColumnType("uuid")
                    .HasColumnName("primary_practitioner_id");

                b.Property<int>("Status")
                    .HasColumnType("integer")
                    .HasColumnName("status");

                b.Property<DateTime?>("UpdatedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("updated_at_utc");

                b.Property<long>("Version")
                    .IsConcurrencyToken()
                    .HasColumnType("bigint")
                    .HasColumnName("version");

                b.HasKey("Id");

                b.HasIndex("AppointmentId")
                    .IsUnique()
                    .HasDatabaseName("ux_encounters_appointment_active")
                    .HasFilter("\"appointment_id\" IS NOT NULL AND \"status\" IN (1, 2, 3)");

                b.HasIndex("DepartmentId")
                    .HasDatabaseName("ix_encounters_department_id");

                b.HasIndex("PatientId")
                    .HasDatabaseName("ix_encounters_patient_id");

                b.HasIndex("PrimaryPractitionerId")
                    .HasDatabaseName("ix_encounters_primary_practitioner_id");

                b.HasIndex("Status")
                    .HasDatabaseName("ix_encounters_status");

                b.ToTable("encounters", "clinical_records");
            });

        modelBuilder.Entity("HospitalManagement.Modules.ClinicalRecords.Domain.EncounterParticipant", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at_utc");

                b.Property<Guid>("EncounterId")
                    .HasColumnType("uuid")
                    .HasColumnName("encounter_id");

                b.Property<DateTime>("JoinedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("joined_at_utc");

                b.Property<DateTime?>("LeftAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("left_at_utc");

                b.Property<Guid>("PractitionerId")
                    .HasColumnType("uuid")
                    .HasColumnName("practitioner_id");

                b.Property<int>("Role")
                    .HasColumnType("integer")
                    .HasColumnName("role");

                b.HasKey("Id");

                b.HasIndex("EncounterId")
                    .HasDatabaseName("ix_encounter_participants_encounter_id");

                b.HasIndex("PractitionerId")
                    .HasDatabaseName("ix_encounter_participants_practitioner_id");

                b.ToTable("encounter_participants", "clinical_records");
            });

        modelBuilder.Entity("HospitalManagement.Modules.ClinicalRecords.Domain.EncounterParticipant", b =>
            {
                b.HasOne("HospitalManagement.Modules.ClinicalRecords.Domain.Encounter", null)
                    .WithMany("Participants")
                    .HasForeignKey("EncounterId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("HospitalManagement.Modules.ClinicalRecords.Domain.Encounter", b =>
            {
                b.Navigation("Participants");
            });
#pragma warning restore 612, 618
    }
}
