<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Denetim izi, erişim kaydı, onay ve mahremiyet modülü.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../HospitalManagement.BuildingBlocks/HospitalManagement.BuildingBlocks.csproj" />
  </ItemGroup>
</Project>
