// <auto-generated />
using System;
using HospitalManagement.Modules.Notifications.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HospitalManagement.Modules.Notifications.Infrastructure.Persistence.Migrations;

[DbContext(typeof(NotificationsDbContext))]
[Migration("20260828004000_InitialNotifications")]
partial class InitialNotifications
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("notifications")
            .HasAnnotation("ProductVersion", "9.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("HospitalManagement.Modules.Notifications.Domain.InAppNotification", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<string>("ActionUrl")
                .HasMaxLength(512)
                .HasColumnType("character varying(512)")
                .HasColumnName("action_url");

            b.Property<DateTime>("CreatedAtUtc")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at_utc");

            b.Property<string>("IdempotencyKey")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("character varying(128)")
                .HasColumnName("idempotency_key");

            b.Property<bool>("IsRead")
                .HasColumnType("boolean")
                .HasColumnName("is_read");

            b.Property<string>("Message")
                .IsRequired()
                .HasMaxLength(2048)
                .HasColumnType("character varying(2048)")
                .HasColumnName("message");

            b.Property<DateTime?>("ReadAtUtc")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("read_at_utc");

            b.Property<Guid>("RecipientPersonId")
                .HasColumnType("uuid")
                .HasColumnName("recipient_person_id");

            b.Property<string>("Title")
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnType("character varying(256)")
                .HasColumnName("title");

            b.HasKey("Id");

            b.HasIndex("IdempotencyKey")
                .IsUnique()
                .HasDatabaseName("ux_in_app_notifications_idempotency_key");

            b.HasIndex("RecipientPersonId", "CreatedAtUtc")
                .HasDatabaseName("ix_in_app_notifications_recipient_created");

            b.ToTable("in_app_notifications", "notifications");
        });

        modelBuilder.Entity("HospitalManagement.Modules.Notifications.Domain.MockDeliveryRecord", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<string>("Body")
                .IsRequired()
                .HasMaxLength(2048)
                .HasColumnType("character varying(2048)")
                .HasColumnName("body");

            b.Property<string>("Channel")
                .IsRequired()
                .HasMaxLength(32)
                .HasColumnType("character varying(32)")
                .HasColumnName("channel");

            b.Property<string>("IdempotencyKey")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("character varying(128)")
                .HasColumnName("idempotency_key");

            b.Property<string>("Recipient")
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnType("character varying(256)")
                .HasColumnName("recipient");

            b.Property<DateTime>("SentAtUtc")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("sent_at_utc");

            b.Property<string>("Subject")
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnType("character varying(256)")
                .HasColumnName("subject");

            b.HasKey("Id");

            b.HasIndex("Recipient", "SentAtUtc")
                .HasDatabaseName("ix_mock_deliveries_recipient_sent");

            b.HasIndex("IdempotencyKey", "Channel")
                .IsUnique()
                .HasDatabaseName("ux_mock_deliveries_idempotency_channel");

            b.ToTable("mock_deliveries", "notifications");
        });

        modelBuilder.Entity("HospitalManagement.Modules.Notifications.Domain.NotificationOutboxEvent", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<DateTime>("CreatedAtUtc")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at_utc");

            b.Property<string>("Error")
                .HasMaxLength(1024)
                .HasColumnType("character varying(1024)")
                .HasColumnName("error");

            b.Property<string>("EventType")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("character varying(64)")
                .HasColumnName("event_type");

            b.Property<string>("IdempotencyKey")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("character varying(128)")
                .HasColumnName("idempotency_key");

            b.Property<string>("Message")
                .IsRequired()
                .HasMaxLength(2048)
                .HasColumnType("character varying(2048)")
                .HasColumnName("message");

            b.Property<DateTime?>("ProcessedAtUtc")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("processed_at_utc");

            b.Property<string>("RecipientEmail")
                .HasMaxLength(256)
                .HasColumnType("character varying(256)")
                .HasColumnName("recipient_email");

            b.Property<Guid>("RecipientPersonId")
                .HasColumnType("uuid")
                .HasColumnName("recipient_person_id");

            b.Property<string>("RecipientPhone")
                .HasMaxLength(32)
                .HasColumnType("character varying(32)")
                .HasColumnName("recipient_phone");

            b.Property<int>("RetryCount")
                .HasColumnType("integer")
                .HasColumnName("retry_count");

            b.Property<string>("Status")
                .IsRequired()
                .HasMaxLength(32)
                .HasColumnType("character varying(32)")
                .HasColumnName("status");

            b.Property<string>("Subject")
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnType("character varying(256)")
                .HasColumnName("subject");

            b.HasKey("Id");

            b.HasIndex("IdempotencyKey")
                .IsUnique()
                .HasDatabaseName("ux_notification_outbox_idempotency_key");

            b.HasIndex("Status", "CreatedAtUtc")
                .HasDatabaseName("ix_notification_outbox_status_created");

            b.ToTable("notification_outbox_events", "notifications");
        });
#pragma warning restore 612, 618
    }
}
