// <auto-generated />
using System;
using HospitalManagement.Modules.Inpatient.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HospitalManagement.Modules.Inpatient.Infrastructure.Persistence.Migrations;

[DbContext(typeof(InpatientDbContext))]
[Migration("20260830001200_AddMedicationAdministrations")]
partial class AddMedicationAdministrations
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("inpatient")
            .HasAnnotation("ProductVersion", "9.0.2")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("HospitalManagement.Modules.Inpatient.Domain.Bed", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("BedNumber")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid?>("CurrentAdmissionId")
                    .HasColumnType("uuid");

                b.Property<Guid?>("CurrentPatientId")
                    .HasColumnType("uuid");

                b.Property<string>("GenderConstraint")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)");

                b.Property<bool>("HasOxygen")
                    .HasColumnType("boolean");

                b.Property<bool>("HasTelemetry")
                    .HasColumnType("boolean");

                b.Property<bool>("HasVentilator")
                    .HasColumnType("boolean");

                b.Property<bool>("IsActive")
                    .HasColumnType("boolean");

                b.Property<string>("IsolationType")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)");

                b.Property<string>("MaintenanceReason")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<Guid>("RoomId")
                    .HasColumnType("uuid");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)");

                b.Property<DateTime?>("UpdatedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("Version")
                    .IsConcurrencyToken()
                    .HasColumnType("integer");

                b.Property<Guid>("WardId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("CurrentAdmissionId");

                b.HasIndex("CurrentPatientId");

                b.HasIndex("RoomId");

                b.HasIndex("Status");

                b.HasIndex("WardId");

                b.HasIndex("WardId", "RoomId", "BedNumber")
                    .IsUnique();

                b.ToTable("beds", "inpatient");
            });

        modelBuilder.Entity("HospitalManagement.Modules.Inpatient.Domain.InpatientAdmission", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<DateTime?>("AcceptedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid?>("AcceptedByUserId")
                    .HasColumnType("uuid");

                b.Property<DateTime?>("AdmittedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid>("AdmittingWardId")
                    .HasColumnType("uuid");

                b.Property<string>("AdmissionNumber")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<string>("AdmissionReason")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<Guid?>("AssignedBedId")
                    .HasColumnType("uuid");

                b.Property<Guid>("AttendingDoctorId")
                    .HasColumnType("uuid");

                b.Property<string>("CancellationReason")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<DateTime?>("CancelledAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid>("DepartmentId")
                    .HasColumnType("uuid");

                b.Property<string>("DiagnosisCode")
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)");

                b.Property<string>("DiagnosisDescription")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<string>("DietType")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<string>("DischargeSummary")
                    .HasMaxLength(2000)
                    .HasColumnType("character varying(2000)");

                b.Property<DateTime?>("DischargedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid?>("EncounterId")
                    .HasColumnType("uuid");

                b.Property<int?>("EstimatedStayDays")
                    .HasColumnType("integer");

                b.Property<int>("FallRiskScore")
                    .HasColumnType("integer");

                b.Property<string>("IsolationRequired")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)");

                b.Property<Guid>("OrderingDoctorId")
                    .HasColumnType("uuid");

                b.Property<Guid>("PatientId")
                    .HasColumnType("uuid");

                b.Property<DateTime>("RequestedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)");

                b.Property<DateTime?>("UpdatedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("Version")
                    .IsConcurrencyToken()
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.HasIndex("AdmissionNumber")
                    .IsUnique();

                b.HasIndex("AdmittingWardId");

                b.HasIndex("AssignedBedId");

                b.HasIndex("DepartmentId");

                b.HasIndex("PatientId");

                b.HasIndex("RequestedAtUtc");

                b.HasIndex("Status");

                b.ToTable("admissions", "inpatient");
            });

        modelBuilder.Entity("HospitalManagement.Modules.Inpatient.Domain.InpatientTransfer", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<DateTime?>("AcceptedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid?>("AcceptedByUserId")
                    .HasColumnType("uuid");

                b.Property<Guid>("AdmissionId")
                    .HasColumnType("uuid");

                b.Property<string>("CancellationReason")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<DateTime?>("CancelledAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid?>("CancelledByUserId")
                    .HasColumnType("uuid");

                b.Property<string>("ClinicalNotes")
                    .HasMaxLength(1000)
                    .HasColumnType("character varying(1000)");

                b.Property<DateTime?>("CompletedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid?>("CompletedByUserId")
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid>("PatientId")
                    .HasColumnType("uuid");

                b.Property<DateTime>("RequestedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid>("RequestedByUserId")
                    .HasColumnType("uuid");

                b.Property<Guid>("SourceBedId")
                    .HasColumnType("uuid");

                b.Property<Guid>("SourceWardId")
                    .HasColumnType("uuid");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)");

                b.Property<Guid?>("TargetBedId")
                    .HasColumnType("uuid");

                b.Property<Guid>("TargetWardId")
                    .HasColumnType("uuid");

                b.Property<string>("TransferReason")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<DateTime?>("UpdatedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("Version")
                    .IsConcurrencyToken()
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.HasIndex("AdmissionId");

                b.HasIndex("PatientId");

                b.HasIndex("RequestedAtUtc");

                b.HasIndex("Status");

                b.ToTable("transfers", "inpatient");
            });

        modelBuilder.Entity("HospitalManagement.Modules.Inpatient.Domain.MedicationAdministration", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<DateTime?>("AdministeredAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid?>("AdministeredByNurseId")
                    .HasColumnType("uuid");

                b.Property<Guid>("AdmissionId")
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Dose")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<string>("MedicationName")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<string>("Notes")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<Guid>("PatientId")
                    .HasColumnType("uuid");

                b.Property<Guid?>("PrescriptionId")
                    .HasColumnType("uuid");

                b.Property<string>("Reason")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<string>("Route")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<DateTime>("ScheduledTimeUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)");

                b.Property<bool>("Verified5Rights")
                    .HasColumnType("boolean");

                b.Property<int>("Version")
                    .IsConcurrencyToken()
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.HasIndex("AdmissionId");

                b.HasIndex("PatientId");

                b.HasIndex("ScheduledTimeUtc");

                b.HasIndex("Status");

                b.ToTable("medication_administrations", "inpatient");
            });

        modelBuilder.Entity("HospitalManagement.Modules.Inpatient.Domain.NursingCarePlan", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<Guid>("AdmissionId")
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid>("CreatedByNurseId")
                    .HasColumnType("uuid");

                b.Property<string>("Goal")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<string>("NursingDiagnosis")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<Guid>("PatientId")
                    .HasColumnType("uuid");

                b.Property<string>("ResolutionNotes")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<DateTime?>("ResolvedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)");

                b.Property<int>("Version")
                    .IsConcurrencyToken()
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.HasIndex("AdmissionId");

                b.HasIndex("PatientId");

                b.HasIndex("Status");

                b.ToTable("nursing_care_plans", "inpatient");
            });

        modelBuilder.Entity("HospitalManagement.Modules.Inpatient.Domain.NursingCareTask", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<string>("CancellationReason")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<DateTime?>("CancelledAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid?>("CancelledByNurseId")
                    .HasColumnType("uuid");

                b.Property<Guid>("CarePlanId")
                    .HasColumnType("uuid");

                b.Property<DateTime?>("CompletedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid?>("CompletedByNurseId")
                    .HasColumnType("uuid");

                b.Property<string>("CompletionNotes")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("DueTimeUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Frequency")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<int>("Version")
                    .IsConcurrencyToken()
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.HasIndex("CarePlanId");

                b.HasIndex("DueTimeUtc");

                b.HasIndex("Status");

                b.ToTable("nursing_care_tasks", "inpatient");
            });

        modelBuilder.Entity("HospitalManagement.Modules.Inpatient.Domain.NursingObservation", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<Guid>("AdmissionId")
                    .HasColumnType("uuid");

                b.Property<decimal?>("BodyTemperatureCelsius")
                    .HasPrecision(4, 1)
                    .HasColumnType("numeric(4,1)");

                b.Property<string>("ClinicalNotes")
                    .HasMaxLength(1000)
                    .HasColumnType("character varying(1000)");

                b.Property<string>("Consciousness")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)");

                b.Property<Guid?>("CorrectedObservationId")
                    .HasColumnType("uuid");

                b.Property<string>("CorrectionReason")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<int?>("DiastolicBp")
                    .HasColumnType("integer");

                b.Property<int?>("DrainOutputMl")
                    .HasColumnType("integer");

                b.Property<int?>("HeartRate")
                    .HasColumnType("integer");

                b.Property<bool>("IsCorrection")
                    .HasColumnType("boolean");

                b.Property<int?>("IvIntakeMl")
                    .HasColumnType("integer");

                b.Property<DateTime>("ObservedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<int?>("OralIntakeMl")
                    .HasColumnType("integer");

                b.Property<int?>("OtherOutputMl")
                    .HasColumnType("integer");

                b.Property<int?>("OxygenSaturationPercent")
                    .HasColumnType("integer");

                b.Property<int?>("PainScale")
                    .HasColumnType("integer");

                b.Property<Guid>("PatientId")
                    .HasColumnType("uuid");

                b.Property<Guid>("RecordedByNurseId")
                    .HasColumnType("uuid");

                b.Property<int?>("RespiratoryRate")
                    .HasColumnType("integer");

                b.Property<int?>("SystolicBp")
                    .HasColumnType("integer");

                b.Property<int?>("UrineOutputMl")
                    .HasColumnType("integer");

                b.Property<int>("Version")
                    .IsConcurrencyToken()
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.HasIndex("AdmissionId");

                b.HasIndex("ObservedAtUtc");

                b.HasIndex("PatientId");

                b.ToTable("nursing_observations", "inpatient");
            });

        modelBuilder.Entity("HospitalManagement.Modules.Inpatient.Domain.Room", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("GenderConstraint")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)");

                b.Property<bool>("IsActive")
                    .HasColumnType("boolean");

                b.Property<bool>("IsNegativePressure")
                    .HasColumnType("boolean");

                b.Property<string>("IsolationType")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)");

                b.Property<string>("RoomNumber")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<DateTime?>("UpdatedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid>("WardId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("WardId", "RoomNumber")
                    .IsUnique();

                b.ToTable("rooms", "inpatient");
            });

        modelBuilder.Entity("HospitalManagement.Modules.Inpatient.Domain.Ward", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Building")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)");

                b.Property<string>("Code")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid>("DepartmentId")
                    .HasColumnType("uuid");

                b.Property<string>("Floor")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<bool>("IsActive")
                    .HasColumnType("boolean");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)");

                b.Property<DateTime?>("UpdatedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("WardType")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)");

                b.HasKey("Id");

                b.HasIndex("Code")
                    .IsUnique();

                b.ToTable("wards", "inpatient");
            });

        modelBuilder.Entity("HospitalManagement.Modules.Inpatient.Domain.Bed", b =>
            {
                b.HasOne("HospitalManagement.Modules.Inpatient.Domain.Room", null)
                    .WithMany("Beds")
                    .HasForeignKey("RoomId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("HospitalManagement.Modules.Inpatient.Domain.NursingCareTask", b =>
            {
                b.HasOne("HospitalManagement.Modules.Inpatient.Domain.NursingCarePlan", null)
                    .WithMany("Tasks")
                    .HasForeignKey("CarePlanId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("HospitalManagement.Modules.Inpatient.Domain.Room", b =>
            {
                b.HasOne("HospitalManagement.Modules.Inpatient.Domain.Ward", null)
                    .WithMany("Rooms")
                    .HasForeignKey("WardId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("HospitalManagement.Modules.Inpatient.Domain.NursingCarePlan", b =>
            {
                b.Navigation("Tasks");
            });

        modelBuilder.Entity("HospitalManagement.Modules.Inpatient.Domain.Room", b =>
            {
                b.Navigation("Beds");
            });

        modelBuilder.Entity("HospitalManagement.Modules.Inpatient.Domain.Ward", b =>
            {
                b.Navigation("Rooms");
            });
#pragma warning restore 612, 618
    }
}
