<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Yatış, servis, oda, yatak ve taburculuk modülü.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../HospitalManagement.BuildingBlocks/HospitalManagement.BuildingBlocks.csproj" />
  </ItemGroup>
</Project>
