// <auto-generated />
using System;
using HospitalManagement.Modules.Scheduling.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HospitalManagement.Modules.Scheduling.Infrastructure.Persistence.Migrations;

[DbContext(typeof(SchedulingDbContext))]
[Migration("20260828002000_AddAppointments")]
partial class AddAppointments
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("scheduling")
            .HasAnnotation("ProductVersion", "9.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("HospitalManagement.Modules.Scheduling.Domain.Appointment", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<DateTime>("AppointmentTimeUtc")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("appointment_time_utc");

            b.Property<string>("CancellationReason")
                .HasMaxLength(512)
                .HasColumnType("character varying(512)")
                .HasColumnName("cancellation_reason");

            b.Property<DateTime?>("CancelledAtUtc")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("cancelled_at_utc");

            b.Property<DateTime?>("CheckedInAtUtc")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("checked_in_at_utc");

            b.Property<DateTime?>("CompletedAtUtc")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("completed_at_utc");

            b.Property<DateTime>("CreatedAtUtc")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at_utc");

            b.Property<Guid>("DepartmentId")
                .HasColumnType("uuid")
                .HasColumnName("department_id");

            b.Property<Guid>("DoctorId")
                .HasColumnType("uuid")
                .HasColumnName("doctor_id");

            b.Property<Guid>("PatientId")
                .HasColumnType("uuid")
                .HasColumnName("patient_id");

            b.Property<string>("ReasonForVisit")
                .HasMaxLength(512)
                .HasColumnType("character varying(512)")
                .HasColumnName("reason_for_visit");

            b.Property<Guid>("SlotId")
                .HasColumnType("uuid")
                .HasColumnName("slot_id");

            b.Property<string>("Status")
                .IsRequired()
                .HasMaxLength(16)
                .HasColumnType("character varying(16)")
                .HasColumnName("status");

            b.Property<DateTime?>("UpdatedAtUtc")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_at_utc");

            b.Property<long>("Version")
                .IsConcurrencyToken()
                .HasColumnType("bigint")
                .HasColumnName("version");

            b.HasKey("Id");

            b.HasIndex("SlotId")
                .HasDatabaseName("ix_appointments_slot_id");

            b.HasIndex("PatientId", "AppointmentTimeUtc")
                .HasDatabaseName("ix_appointments_patient_time");

            b.HasIndex("DoctorId", "AppointmentTimeUtc", "Status")
                .HasDatabaseName("ix_appointments_doctor_time_status");

            b.HasIndex("DepartmentId", "AppointmentTimeUtc", "Status")
                .HasDatabaseName("ix_appointments_dept_time_status");

            b.ToTable("appointments", "scheduling");
        });

        modelBuilder.Entity("HospitalManagement.Modules.Scheduling.Domain.AppointmentSlot", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<DateTime>("CreatedAtUtc")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at_utc");

            b.Property<Guid>("DepartmentId")
                .HasColumnType("uuid")
                .HasColumnName("department_id");

            b.Property<Guid>("DoctorId")
                .HasColumnType("uuid")
                .HasColumnName("doctor_id");

            b.Property<DateTime>("EndUtc")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("end_utc");

            b.Property<Guid?>("HeldByPersonId")
                .HasColumnType("uuid")
                .HasColumnName("held_by_person_id");

            b.Property<DateTime?>("HoldExpirationUtc")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("hold_expiration_utc");

            b.Property<Guid?>("ScheduleId")
                .HasColumnType("uuid")
                .HasColumnName("schedule_id");

            b.Property<DateTime>("StartUtc")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("start_utc");

            b.Property<string>("Status")
                .IsRequired()
                .HasMaxLength(16)
                .HasColumnType("character varying(16)")
                .HasColumnName("status");

            b.Property<DateTime?>("UpdatedAtUtc")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_at_utc");

            b.Property<long>("Version")
                .IsConcurrencyToken()
                .HasColumnType("bigint")
                .HasColumnName("version");

            b.HasKey("Id");

            b.HasIndex("DepartmentId", "StartUtc", "Status")
                .HasDatabaseName("ix_appointment_slots_dept_start_status");

            b.HasIndex("DoctorId", "StartUtc", "Status")
                .HasDatabaseName("ix_appointment_slots_doctor_start_status");

            b.HasIndex("DoctorId", "StartUtc")
                .IsUnique()
                .HasDatabaseName("ux_appointment_slots_doctor_start");

            b.ToTable("appointment_slots", "scheduling");
        });

        modelBuilder.Entity("HospitalManagement.Modules.Scheduling.Domain.DoctorLeaveBlock", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<DateTime>("CreatedAtUtc")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at_utc");

            b.Property<Guid>("DoctorId")
                .HasColumnType("uuid")
                .HasColumnName("doctor_id");

            b.Property<DateTime>("EndUtc")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("end_utc");

            b.Property<bool>("IsActive")
                .HasColumnType("boolean")
                .HasColumnName("is_active");

            b.Property<string>("Reason")
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnType("character varying(256)")
                .HasColumnName("reason");

            b.Property<DateTime>("StartUtc")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("start_utc");

            b.HasKey("Id");

            b.HasIndex("DoctorId", "StartUtc", "EndUtc", "IsActive")
                .HasDatabaseName("ix_doctor_leave_blocks_doctor_dates");

            b.ToTable("doctor_leave_blocks", "scheduling");
        });

        modelBuilder.Entity("HospitalManagement.Modules.Scheduling.Domain.DoctorSchedule", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<DateTime>("CreatedAtUtc")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at_utc");

            b.Property<string>("DayOfWeek")
                .IsRequired()
                .HasMaxLength(16)
                .HasColumnType("character varying(16)")
                .HasColumnName("day_of_week");

            b.Property<Guid>("DepartmentId")
                .HasColumnType("uuid")
                .HasColumnName("department_id");

            b.Property<Guid>("DoctorId")
                .HasColumnType("uuid")
                .HasColumnName("doctor_id");

            b.Property<TimeOnly>("EndTime")
                .HasColumnType("time without time zone")
                .HasColumnName("end_time");

            b.Property<bool>("IsActive")
                .HasColumnType("boolean")
                .HasColumnName("is_active");

            b.Property<int>("SlotDurationMinutes")
                .HasColumnType("integer")
                .HasColumnName("slot_duration_minutes");

            b.Property<TimeOnly>("StartTime")
                .HasColumnType("time without time zone")
                .HasColumnName("start_time");

            b.Property<DateTime?>("UpdatedAtUtc")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_at_utc");

            b.HasKey("Id");

            b.HasIndex("DoctorId", "DayOfWeek", "IsActive")
                .HasDatabaseName("ix_doctor_schedules_doctor_day");

            b.ToTable("doctor_schedules", "scheduling");
        });

        modelBuilder.Entity("HospitalManagement.Modules.Scheduling.Domain.ScheduleBreak", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<TimeOnly>("EndTime")
                .HasColumnType("time without time zone")
                .HasColumnName("end_time");

            b.Property<string>("Reason")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("character varying(128)")
                .HasColumnName("reason");

            b.Property<Guid>("ScheduleId")
                .HasColumnType("uuid")
                .HasColumnName("schedule_id");

            b.Property<TimeOnly>("StartTime")
                .HasColumnType("time without time zone")
                .HasColumnName("start_time");

            b.HasKey("Id");

            b.HasIndex("ScheduleId")
                .HasDatabaseName("ix_schedule_breaks_schedule_id");

            b.ToTable("schedule_breaks", "scheduling");
        });

        modelBuilder.Entity("HospitalManagement.Modules.Scheduling.Domain.ScheduleBreak", b =>
        {
            b.HasOne("HospitalManagement.Modules.Scheduling.Domain.DoctorSchedule", null)
                .WithMany("Breaks")
                .HasForeignKey("ScheduleId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("HospitalManagement.Modules.Scheduling.Domain.DoctorSchedule", b =>
        {
            b.Navigation("Breaks");
        });
#pragma warning restore 612, 618
    }
}
