// <auto-generated />
using System;
using HospitalManagement.Modules.SpecialtyCare.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HospitalManagement.Modules.SpecialtyCare.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SpecialtyCareDbContext))]
    [Migration("20260901124030_LinkHomeHealthVisitsToEncounters")]
    partial class LinkHomeHealthVisitsToEncounters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("specialty")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HospitalManagement.Modules.SpecialtyCare.Domain.HomeHealth.HomeHealthVisit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AddressDetail")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("AssignedStaffId")
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ClinicalNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("EncounterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ProtocolNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("RequestedByStaffId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RequestedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ScheduledDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("VisitCompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("VisitStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VitalsSummaryNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedStaffId");

                    b.HasIndex("EncounterId")
                        .IsUnique()
                        .HasDatabaseName("UX_HomeHealthVisits_EncounterId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ProtocolNumber")
                        .IsUnique();

                    b.HasIndex("ScheduledDateUtc");

                    b.HasIndex("Status");

                    b.ToTable("HomeHealthVisits", "specialty");
                });

            modelBuilder.Entity("HospitalManagement.Modules.SpecialtyCare.Domain.Obstetrics.AntenatalVisit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ClinicalNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DiastolicBpMmHg")
                        .HasColumnType("integer");

                    b.Property<string>("EdemaLevel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("EncounterId")
                        .HasColumnType("uuid");

                    b.Property<int?>("FetalHeartRateBpm")
                        .HasColumnType("integer");

                    b.Property<string>("FetalPresentation")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal?>("FundalHeightCm")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)");

                    b.Property<int>("GestationalAgeDays")
                        .HasColumnType("integer");

                    b.Property<int>("GestationalAgeWeeks")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MaternalWeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime?>("NextVisitRecommendedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PregnancyEpisodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SystolicBpMmHg")
                        .HasColumnType("integer");

                    b.Property<bool>("UrineGlucosePresent")
                        .HasColumnType("boolean");

                    b.Property<bool>("UrineProteinPresent")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("VisitDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EncounterId");

                    b.HasIndex("PregnancyEpisodeId");

                    b.HasIndex("VisitDateUtc");

                    b.ToTable("AntenatalVisits", "specialty");
                });

            modelBuilder.Entity("HospitalManagement.Modules.SpecialtyCare.Domain.Obstetrics.DeliveryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssistingMidwifeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttendingDoctorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("DeliveryProtocolNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DeliverySummaryNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("DeliveryTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EncounterId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("EstimatedBloodLossMl")
                        .HasPrecision(6, 1)
                        .HasColumnType("numeric(6,1)");

                    b.Property<int>("GestationalAgeDays")
                        .HasColumnType("integer");

                    b.Property<int>("GestationalAgeWeeks")
                        .HasColumnType("integer");

                    b.Property<string>("MaternalComplicationsNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("MotherPatientId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PediatricianDoctorId")
                        .HasColumnType("uuid");

                    b.Property<string>("PerinealTear")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("PregnancyEpisodeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryProtocolNumber")
                        .IsUnique();

                    b.HasIndex("DeliveryTimeUtc");

                    b.HasIndex("MotherPatientId");

                    b.HasIndex("PregnancyEpisodeId");

                    b.ToTable("DeliveryRecords", "specialty");
                });

            modelBuilder.Entity("HospitalManagement.Modules.SpecialtyCare.Domain.Obstetrics.NewbornRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("ApgarScore10Min")
                        .HasColumnType("integer");

                    b.Property<int>("ApgarScore1Min")
                        .HasColumnType("integer");

                    b.Property<int>("ApgarScore5Min")
                        .HasColumnType("integer");

                    b.Property<decimal>("BirthLengthCm")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)");

                    b.Property<int>("BirthOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("BirthTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("BirthWeightGrams")
                        .HasPrecision(6, 1)
                        .HasColumnType("numeric(6,1)");

                    b.Property<string>("ComplicationsNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("CordBloodPh")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeliveryRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("HeadCircumferenceCm")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)");

                    b.Property<Guid>("NewbornPatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResuscitationGiven")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("BirthTimeUtc");

                    b.HasIndex("DeliveryRecordId");

                    b.HasIndex("NewbornPatientId")
                        .IsUnique()
                        .HasDatabaseName("UX_NewbornRecords_NewbornPatientId");

                    b.ToTable("NewbornRecords", "specialty");
                });

            modelBuilder.Entity("HospitalManagement.Modules.SpecialtyCare.Domain.Obstetrics.PregnancyEpisode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Abortus")
                        .HasColumnType("integer");

                    b.Property<Guid?>("AssignedDoctorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedMidwifeId")
                        .HasColumnType("uuid");

                    b.Property<string>("BloodGroupAndRh")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EpisodeProtocolNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("EstimatedDeliveryDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Gravida")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastMenstrualPeriodUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LivingChildren")
                        .HasColumnType("integer");

                    b.Property<Guid>("OpeningEncounterId")
                        .HasColumnType("uuid");

                    b.Property<int>("Para")
                        .HasColumnType("integer");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("RiskCategory")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("RiskFactorsNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeProtocolNumber")
                        .IsUnique();

                    b.HasIndex("EstimatedDeliveryDateUtc");

                    b.HasIndex("OpeningEncounterId");

                    b.HasIndex("PatientId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Active'");

                    b.HasIndex("RiskCategory");

                    b.HasIndex("Status");

                    b.ToTable("PregnancyEpisodes", "specialty");
                });

            modelBuilder.Entity("HospitalManagement.Modules.SpecialtyCare.Domain.Odontology.DentalExaminationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ChiefComplaint")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DentistId")
                        .HasColumnType("uuid");

                    b.Property<string>("DiagnosisNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("EncounterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExaminationDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExaminationProtocolNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("TreatmentPlanSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ExaminationDateUtc");

                    b.HasIndex("ExaminationProtocolNumber")
                        .IsUnique();

                    b.HasIndex("PatientId");

                    b.ToTable("DentalExaminations", "specialty");
                });

            modelBuilder.Entity("HospitalManagement.Modules.SpecialtyCare.Domain.Odontology.DentalProcedure", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ClinicalNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("CompletedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EncounterId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("EstimatedCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PerformedByDoctorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProcedureCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ProcedureName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ProcedureProtocolNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("ScheduledDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Surfaces")
                        .HasColumnType("integer");

                    b.Property<int?>("ToothNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("ProcedureProtocolNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("ToothNumber");

                    b.ToTable("DentalProcedures", "specialty");
                });

            modelBuilder.Entity("HospitalManagement.Modules.SpecialtyCare.Domain.Odontology.DentalToothCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AffectedSurfaces")
                        .HasColumnType("integer");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecordedByStaffId")
                        .HasColumnType("uuid");

                    b.Property<int>("ToothNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAtUtc");

                    b.HasIndex("PatientId", "ToothNumber");

                    b.HasIndex("PatientId", "ToothNumber", "Version")
                        .IsUnique();

                    b.ToTable("DentalToothConditions", "specialty");
                });

            modelBuilder.Entity("HospitalManagement.Modules.SpecialtyCare.Domain.Obstetrics.AntenatalVisit", b =>
                {
                    b.HasOne("HospitalManagement.Modules.SpecialtyCare.Domain.Obstetrics.PregnancyEpisode", null)
                        .WithMany("AntenatalVisits")
                        .HasForeignKey("PregnancyEpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HospitalManagement.Modules.SpecialtyCare.Domain.Obstetrics.NewbornRecord", b =>
                {
                    b.HasOne("HospitalManagement.Modules.SpecialtyCare.Domain.Obstetrics.DeliveryRecord", null)
                        .WithMany("Newborns")
                        .HasForeignKey("DeliveryRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HospitalManagement.Modules.SpecialtyCare.Domain.Obstetrics.DeliveryRecord", b =>
                {
                    b.Navigation("Newborns");
                });

            modelBuilder.Entity("HospitalManagement.Modules.SpecialtyCare.Domain.Obstetrics.PregnancyEpisode", b =>
                {
                    b.Navigation("AntenatalVisits");
                });
#pragma warning restore 612, 618
        }
    }
}
