// <auto-generated />
using System;
using HospitalManagement.Modules.Organization.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HospitalManagement.Modules.Organization.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrganizationDbContext))]
    [Migration("20260831135544_AddGeneralSurgeryDepartment")]
    partial class AddGeneralSurgeryDepartment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("organization")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HospitalManagement.Modules.Organization.Domain.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("display_name");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("facility_id");

                    b.Property<Guid>("HospitalId")
                        .HasColumnType("uuid")
                        .HasColumnName("hospital_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid?>("ParentDepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_department_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_departments");

                    b.HasAlternateKey("HospitalId", "Id")
                        .HasName("ak_departments_hospital_id_id");

                    b.HasAlternateKey("HospitalId", "FacilityId", "Id")
                        .HasName("ak_departments_hospital_id_facility_id_id");

                    b.HasIndex("HospitalId", "FacilityId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_departments_hospital_facility_code");

                    b.HasIndex("HospitalId", "FacilityId", "ParentDepartmentId");

                    b.ToTable("departments", "organization");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            Category = "Clinical",
                            Code = "DEMO-CLINICAL-SERVICES",
                            CreatedAtUtc = new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "DEMO Klinik Hizmetler",
                            FacilityId = new Guid("20000000-0000-0000-0000-000000000001"),
                            HospitalId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            Category = "Clinical",
                            Code = "DEMO-INTERNAL-MEDICINE",
                            CreatedAtUtc = new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "DEMO İç Hastalıkları Bölümü",
                            FacilityId = new Guid("20000000-0000-0000-0000-000000000001"),
                            HospitalId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            ParentDepartmentId = new Guid("30000000-0000-0000-0000-000000000001"),
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            Category = "Clinical",
                            Code = "DEMO-CARDIOLOGY",
                            CreatedAtUtc = new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "DEMO Kardiyoloji Bölümü",
                            FacilityId = new Guid("20000000-0000-0000-0000-000000000001"),
                            HospitalId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            ParentDepartmentId = new Guid("30000000-0000-0000-0000-000000000001"),
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000008"),
                            Category = "Clinical",
                            Code = "DEMO-INTENSIVE-CARE",
                            CreatedAtUtc = new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "DEMO Yoğun Bakım Bölümü",
                            FacilityId = new Guid("20000000-0000-0000-0000-000000000001"),
                            HospitalId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            ParentDepartmentId = new Guid("30000000-0000-0000-0000-000000000001"),
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000009"),
                            Category = "Clinical",
                            Code = "DEMO-GENERAL-SURGERY",
                            CreatedAtUtc = new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "DEMO Genel Cerrahi Bölümü",
                            FacilityId = new Guid("20000000-0000-0000-0000-000000000001"),
                            HospitalId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            ParentDepartmentId = new Guid("30000000-0000-0000-0000-000000000001"),
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            Category = "Diagnostic",
                            Code = "DEMO-DIAGNOSTIC-SERVICES",
                            CreatedAtUtc = new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "DEMO Tanı Hizmetleri",
                            FacilityId = new Guid("20000000-0000-0000-0000-000000000001"),
                            HospitalId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            Category = "Diagnostic",
                            Code = "DEMO-LABORATORY",
                            CreatedAtUtc = new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "DEMO Laboratuvar Bölümü",
                            FacilityId = new Guid("20000000-0000-0000-0000-000000000001"),
                            HospitalId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            ParentDepartmentId = new Guid("30000000-0000-0000-0000-000000000004"),
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000006"),
                            Category = "Diagnostic",
                            Code = "DEMO-RADIOLOGY",
                            CreatedAtUtc = new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "DEMO Radyoloji Bölümü",
                            FacilityId = new Guid("20000000-0000-0000-0000-000000000001"),
                            HospitalId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            ParentDepartmentId = new Guid("30000000-0000-0000-0000-000000000004"),
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000007"),
                            Category = "Operational",
                            Code = "DEMO-PHARMACY",
                            CreatedAtUtc = new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "DEMO Eczane Bölümü",
                            FacilityId = new Guid("20000000-0000-0000-0000-000000000001"),
                            HospitalId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Version = 1L
                        });
                });

            modelBuilder.Entity("HospitalManagement.Modules.Organization.Domain.Facility", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("display_name");

                    b.Property<Guid>("HospitalId")
                        .HasColumnType("uuid")
                        .HasColumnName("hospital_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_facilities");

                    b.HasAlternateKey("HospitalId", "Id")
                        .HasName("ak_facilities_hospital_id_id");

                    b.HasIndex("HospitalId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_facilities_hospital_id_code");

                    b.ToTable("facilities", "organization");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Code = "DEMO-CENTRAL",
                            CreatedAtUtc = new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "DEMO Merkez Şube",
                            HospitalId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Version = 1L
                        });
                });

            modelBuilder.Entity("HospitalManagement.Modules.Organization.Domain.Hospital", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_hospitals");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_hospitals_code");

                    b.ToTable("hospitals", "organization");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Code = "DEMO-HOSPITAL",
                            CreatedAtUtc = new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "DEMO Eğitim Hastanesi",
                            IsActive = true,
                            Version = 1L
                        });
                });

            modelBuilder.Entity("HospitalManagement.Modules.Organization.Domain.Specialty", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("display_name");

                    b.Property<Guid>("HospitalId")
                        .HasColumnType("uuid")
                        .HasColumnName("hospital_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_specialties");

                    b.HasAlternateKey("HospitalId", "Id")
                        .HasName("ak_specialties_hospital_id_id");

                    b.HasIndex("HospitalId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_specialties_hospital_id_code");

                    b.ToTable("specialties", "organization");

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            Code = "DEMO-INTERNAL-MEDICINE",
                            CreatedAtUtc = new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "DEMO İç Hastalıkları",
                            HospitalId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            Code = "DEMO-CARDIOLOGY",
                            CreatedAtUtc = new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "DEMO Kardiyoloji",
                            HospitalId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            Code = "DEMO-MEDICAL-BIOCHEMISTRY",
                            CreatedAtUtc = new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "DEMO Tıbbi Biyokimya",
                            HospitalId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000004"),
                            Code = "DEMO-RADIOLOGY",
                            CreatedAtUtc = new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "DEMO Radyoloji",
                            HospitalId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000005"),
                            Code = "DEMO-GENERAL-SURGERY",
                            CreatedAtUtc = new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "DEMO Genel Cerrahi",
                            HospitalId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Version = 1L
                        });
                });

            modelBuilder.Entity("HospitalManagement.Modules.Organization.Domain.StaffDepartmentAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<DateTime?>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at_utc");

                    b.Property<Guid>("HospitalId")
                        .HasColumnType("uuid")
                        .HasColumnName("hospital_id");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<Guid>("StaffProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_profile_id");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_staff_department_assignments");

                    b.HasIndex("StaffProfileId")
                        .IsUnique()
                        .HasDatabaseName("ux_staff_assignments_active_primary")
                        .HasFilter("is_primary AND ends_at_utc IS NULL");

                    b.HasIndex("HospitalId", "DepartmentId");

                    b.HasIndex("HospitalId", "StaffProfileId");

                    b.HasIndex("StaffProfileId", "DepartmentId")
                        .IsUnique()
                        .HasDatabaseName("ux_staff_assignments_active_staff_department")
                        .HasFilter("ends_at_utc IS NULL");

                    b.ToTable("staff_department_assignments", "organization", t =>
                        {
                            t.HasCheckConstraint("ck_staff_department_assignments_valid_interval", "ends_at_utc IS NULL OR ends_at_utc > starts_at_utc");
                        });
                });

            modelBuilder.Entity("HospitalManagement.Modules.Organization.Domain.StaffProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("HospitalId")
                        .HasColumnType("uuid")
                        .HasColumnName("hospital_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<Guid?>("PrimarySpecialtyId")
                        .HasColumnType("uuid")
                        .HasColumnName("primary_specialty_id");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("profession");

                    b.Property<string>("StaffNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("staff_number");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_staff_profiles");

                    b.HasAlternateKey("HospitalId", "Id")
                        .HasName("ak_staff_profiles_hospital_id_id");

                    b.HasIndex("HospitalId", "PersonId")
                        .IsUnique()
                        .HasDatabaseName("ux_staff_profiles_hospital_id_person_id");

                    b.HasIndex("HospitalId", "PrimarySpecialtyId");

                    b.HasIndex("HospitalId", "StaffNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_staff_profiles_hospital_id_staff_number");

                    b.ToTable("staff_profiles", "organization");
                });

            modelBuilder.Entity("HospitalManagement.Modules.Organization.Domain.Department", b =>
                {
                    b.HasOne("HospitalManagement.Modules.Organization.Domain.Facility", null)
                        .WithMany()
                        .HasForeignKey("HospitalId", "FacilityId")
                        .HasPrincipalKey("HospitalId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_departments_facilities_hospital_id_facility_id");

                    b.HasOne("HospitalManagement.Modules.Organization.Domain.Department", null)
                        .WithMany()
                        .HasForeignKey("HospitalId", "FacilityId", "ParentDepartmentId")
                        .HasPrincipalKey("HospitalId", "FacilityId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_departments_parent_department");
                });

            modelBuilder.Entity("HospitalManagement.Modules.Organization.Domain.Facility", b =>
                {
                    b.HasOne("HospitalManagement.Modules.Organization.Domain.Hospital", null)
                        .WithMany()
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_facilities_hospitals_hospital_id");
                });

            modelBuilder.Entity("HospitalManagement.Modules.Organization.Domain.Specialty", b =>
                {
                    b.HasOne("HospitalManagement.Modules.Organization.Domain.Hospital", null)
                        .WithMany()
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_specialties_hospitals_hospital_id");
                });

            modelBuilder.Entity("HospitalManagement.Modules.Organization.Domain.StaffDepartmentAssignment", b =>
                {
                    b.HasOne("HospitalManagement.Modules.Organization.Domain.Department", null)
                        .WithMany()
                        .HasForeignKey("HospitalId", "DepartmentId")
                        .HasPrincipalKey("HospitalId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_staff_assignments_departments_hospital_scope");

                    b.HasOne("HospitalManagement.Modules.Organization.Domain.StaffProfile", null)
                        .WithMany()
                        .HasForeignKey("HospitalId", "StaffProfileId")
                        .HasPrincipalKey("HospitalId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_staff_assignments_staff_profiles_hospital_scope");
                });

            modelBuilder.Entity("HospitalManagement.Modules.Organization.Domain.StaffProfile", b =>
                {
                    b.HasOne("HospitalManagement.Modules.Organization.Domain.Hospital", null)
                        .WithMany()
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_staff_profiles_hospitals_hospital_id");

                    b.HasOne("HospitalManagement.Modules.Organization.Domain.Specialty", null)
                        .WithMany()
                        .HasForeignKey("HospitalId", "PrimarySpecialtyId")
                        .HasPrincipalKey("HospitalId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_staff_profiles_specialties_primary_specialty");
                });
#pragma warning restore 612, 618
        }
    }
}
