<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Kimlik doğrulama, kullanıcı, rol, izin ve erişim bağlamı modülü.</Description>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../HospitalManagement.BuildingBlocks/HospitalManagement.BuildingBlocks.csproj" />
  </ItemGroup>
</Project>
