// <auto-generated />
using System;
using HospitalManagement.Modules.Diagnostics.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HospitalManagement.Modules.Diagnostics.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DiagnosticsDbContext))]
    [Migration("20260830001440_AddCriticalResultNotificationIdempotency")]
    partial class AddCriticalResultNotificationIdempotency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("diagnostics")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HospitalManagement.Modules.Diagnostics.Domain.BloodUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BloodGroup")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("blood_group");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("DonationDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("donation_date_utc");

                    b.Property<DateTime>("ExpiryDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_date_utc");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("product_type");

                    b.Property<Guid?>("ReservedForPatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("reserved_for_patient_id");

                    b.Property<DateTime?>("ReservedUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reserved_until_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("StorageLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("storage_location");

                    b.Property<string>("UnitNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit_number");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<int>("VolumeMl")
                        .HasColumnType("integer")
                        .HasColumnName("volume_ml");

                    b.HasKey("Id");

                    b.HasIndex("BloodGroup");

                    b.HasIndex("ProductType");

                    b.HasIndex("ReservedForPatientId");

                    b.HasIndex("Status");

                    b.HasIndex("UnitNumber")
                        .IsUnique();

                    b.ToTable("blood_units", "diagnostics");
                });

            modelBuilder.Entity("HospitalManagement.Modules.Diagnostics.Domain.CriticalResultNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcknowledgedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at_utc");

                    b.Property<Guid?>("AcknowledgedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("acknowledged_by_user_id");

                    b.Property<string>("AcknowledgmentNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("acknowledgment_notes");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DiagnosticOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("diagnostic_order_id");

                    b.Property<Guid>("DiagnosticOrderItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("diagnostic_order_item_id");

                    b.Property<DateTime?>("EscalatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("escalated_at_utc");

                    b.Property<int>("EscalationLevel")
                        .HasColumnType("integer")
                        .HasColumnName("escalation_level");

                    b.Property<string>("EscalationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("escalation_reason");

                    b.Property<string>("Flag")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("flag");

                    b.Property<Guid>("LabResultId")
                        .HasColumnType("uuid")
                        .HasColumnName("lab_result_id");

                    b.Property<decimal?>("NumericValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("numeric_value");

                    b.Property<string>("ParameterCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("parameter_code");

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("parameter_name");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<Guid?>("ResponsibleDoctorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("responsible_doctor_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("StringValue")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("string_value");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosticOrderId");

                    b.HasIndex("LabResultId");

                    b.HasIndex("PatientId");

                    b.HasIndex("Status");

                    b.HasIndex("LabResultId", "ParameterCode")
                        .IsUnique();

                    b.ToTable("critical_result_notifications", "diagnostics");
                });

            modelBuilder.Entity("HospitalManagement.Modules.Diagnostics.Domain.CrossmatchRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AllocatedBloodUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("allocated_blood_unit_id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<string>("CompatibilityResult")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("compatibility_result");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DiagnosticOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("diagnostic_order_id");

                    b.Property<Guid>("DiagnosticOrderItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("diagnostic_order_item_id");

                    b.Property<string>("PatientBloodGroup")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("patient_blood_group");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("RequestedProductType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("requested_product_type");

                    b.Property<DateTime?>("RequiredByUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("required_by_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("TechnicianNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("technician_notes");

                    b.Property<DateTime?>("TestedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tested_at_utc");

                    b.Property<Guid?>("TestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("tested_by_user_id");

                    b.Property<int>("UnitsRequested")
                        .HasColumnType("integer")
                        .HasColumnName("units_requested");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CompatibilityResult");

                    b.HasIndex("DiagnosticOrderId");

                    b.HasIndex("DiagnosticOrderItemId");

                    b.HasIndex("PatientId");

                    b.HasIndex("Status");

                    b.ToTable("crossmatch_requests", "diagnostics");
                });

            modelBuilder.Entity("HospitalManagement.Modules.Diagnostics.Domain.DiagnosticOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<string>("ClinicalIndication")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("clinical_indication");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<Guid>("EncounterId")
                        .HasColumnType("uuid")
                        .HasColumnName("encounter_id");

                    b.Property<string>("EnteredInErrorReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("entered_in_error_reason");

                    b.Property<string>("OrderNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("order_notes");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_number");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("order_type");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<DateTime?>("PlacedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("placed_at_utc");

                    b.Property<Guid>("PlacingDoctorId")
                        .HasColumnType("uuid")
                        .HasColumnName("placing_doctor_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("priority");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("EncounterId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("OrderType");

                    b.HasIndex("PatientId");

                    b.HasIndex("Status");

                    b.ToTable("diagnostic_orders", "diagnostics");
                });

            modelBuilder.Entity("HospitalManagement.Modules.Diagnostics.Domain.DiagnosticOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CatalogCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("catalog_code");

                    b.Property<string>("CatalogItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("catalog_item_name");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DiagnosticOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("diagnostic_order_id");

                    b.Property<string>("SpecialInstructions")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("special_instructions");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("CatalogCode");

                    b.HasIndex("DiagnosticOrderId");

                    b.ToTable("diagnostic_order_items", "diagnostics");
                });

            modelBuilder.Entity("HospitalManagement.Modules.Diagnostics.Domain.LabCatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CatalogVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("catalog_version");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("ContainerType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("container_type");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPanel")
                        .HasColumnType("boolean")
                        .HasColumnName("is_panel");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("SpecimenType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("specimen_type");

                    b.Property<int>("TurnaroundMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("turnaround_minutes");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("lab_catalog_items", "diagnostics");
                });

            modelBuilder.Entity("HospitalManagement.Modules.Diagnostics.Domain.LabCatalogParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<decimal?>("CriticalHigh")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("critical_high");

                    b.Property<decimal?>("CriticalLow")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("critical_low");

                    b.Property<Guid>("LabCatalogItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("lab_catalog_item_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal?>("ReferenceRangeHigh")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("reference_range_high");

                    b.Property<decimal?>("ReferenceRangeLow")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("reference_range_low");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("value_type");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("LabCatalogItemId");

                    b.ToTable("lab_catalog_parameters", "diagnostics");
                });

            modelBuilder.Entity("HospitalManagement.Modules.Diagnostics.Domain.LabResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CatalogCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("catalog_code");

                    b.Property<string>("CatalogItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("catalog_item_name");

                    b.Property<string>("ClinicalNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("clinical_notes");

                    b.Property<DateTime?>("ClinicallyApprovedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("clinically_approved_at_utc");

                    b.Property<Guid?>("ClinicallyApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("clinically_approved_by_user_id");

                    b.Property<string>("CorrectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("correction_reason");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DiagnosticOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("diagnostic_order_id");

                    b.Property<Guid>("DiagnosticOrderItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("diagnostic_order_item_id");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<Guid?>("PreviousResultId")
                        .HasColumnType("uuid")
                        .HasColumnName("previous_result_id");

                    b.Property<Guid?>("SpecimenId")
                        .HasColumnType("uuid")
                        .HasColumnName("specimen_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("TechnicallyApprovedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("technically_approved_at_utc");

                    b.Property<Guid?>("TechnicallyApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("technically_approved_by_user_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("DiagnosticOrderId");

                    b.HasIndex("DiagnosticOrderItemId");

                    b.HasIndex("PatientId");

                    b.HasIndex("Status");

                    b.ToTable("lab_results", "diagnostics");
                });

            modelBuilder.Entity("HospitalManagement.Modules.Diagnostics.Domain.LabResultItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Flag")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("flag");

                    b.Property<Guid>("LabResultId")
                        .HasColumnType("uuid")
                        .HasColumnName("lab_result_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<decimal?>("NumericValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("numeric_value");

                    b.Property<string>("ParameterCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("parameter_code");

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("parameter_name");

                    b.Property<decimal?>("ReferenceRangeHigh")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("reference_range_high");

                    b.Property<decimal?>("ReferenceRangeLow")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("reference_range_low");

                    b.Property<string>("ReferenceRangeText")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reference_range_text");

                    b.Property<string>("StringValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("string_value");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("LabResultId");

                    b.HasIndex("ParameterCode");

                    b.ToTable("lab_result_items", "diagnostics");
                });

            modelBuilder.Entity("HospitalManagement.Modules.Diagnostics.Domain.PathologyCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnatomicSite")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("anatomic_site");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<string>("ClinicalHistoryAndDiagnosis")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("clinical_history_and_diagnosis");

                    b.Property<string>("CorrectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("correction_reason");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DiagnosticOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("diagnostic_order_id");

                    b.Property<Guid>("DiagnosticOrderItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("diagnostic_order_item_id");

                    b.Property<string>("FixativeUsed")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fixative_used");

                    b.Property<string>("GrossDescription")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("gross_description");

                    b.Property<DateTime?>("GrossExamAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("gross_exam_at_utc");

                    b.Property<Guid?>("GrossExamByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("gross_exam_by_user_id");

                    b.Property<string>("MicroscopicDescription")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("microscopic_description");

                    b.Property<DateTime?>("MicroscopicExamAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("microscopic_exam_at_utc");

                    b.Property<Guid?>("MicroscopicExamByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("microscopic_exam_by_user_id");

                    b.Property<string>("PathologicalDiagnosis")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("pathological_diagnosis");

                    b.Property<Guid?>("PathologistUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("pathologist_user_id");

                    b.Property<string>("PathologyNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("pathology_number");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<Guid?>("PreviousCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("previous_case_id");

                    b.Property<DateTime?>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<Guid?>("ReceivedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("received_by_user_id");

                    b.Property<DateTime?>("ReportDraftedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("report_drafted_at_utc");

                    b.Property<DateTime?>("ReportFinalizedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("report_finalized_at_utc");

                    b.Property<string>("SpecimenType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("specimen_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosticOrderId");

                    b.HasIndex("DiagnosticOrderItemId");

                    b.HasIndex("PathologyNumber")
                        .IsUnique();

                    b.HasIndex("PatientId");

                    b.HasIndex("Status");

                    b.ToTable("pathology_cases", "diagnostics");
                });

            modelBuilder.Entity("HospitalManagement.Modules.Diagnostics.Domain.RadiologyCatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BodySite")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("body_site");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<bool>("ContrastRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("contrast_required");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("EstimatedDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_duration_minutes");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Modality")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("modality");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PreparationInstructions")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("preparation_instructions");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("Modality");

                    b.ToTable("radiology_catalog_items", "diagnostics");
                });

            modelBuilder.Entity("HospitalManagement.Modules.Diagnostics.Domain.RadiologyStudy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessionNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("accession_number");

                    b.Property<DateTime?>("AddendumAddedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("addendum_added_at_utc");

                    b.Property<Guid?>("AddendumByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("addendum_by_user_id");

                    b.Property<string>("AddendumText")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("addendum_text");

                    b.Property<string>("BodySite")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("body_site");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DiagnosticOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("diagnostic_order_id");

                    b.Property<Guid>("DiagnosticOrderItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("diagnostic_order_item_id");

                    b.Property<string>("Impression")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("impression");

                    b.Property<string>("Modality")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("modality");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<DateTime?>("PerformedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at_utc");

                    b.Property<string>("ProcedureCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("procedure_code");

                    b.Property<string>("ProcedureName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("procedure_name");

                    b.Property<Guid?>("RadiologistUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("radiologist_user_id");

                    b.Property<DateTime?>("ReportDraftedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("report_drafted_at_utc");

                    b.Property<DateTime?>("ReportFinalizedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("report_finalized_at_utc");

                    b.Property<string>("ReportText")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("report_text");

                    b.Property<DateTime?>("ScheduledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("TechnicianNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("technician_notes");

                    b.Property<Guid?>("TechnicianUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("technician_user_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("AccessionNumber")
                        .IsUnique();

                    b.HasIndex("DiagnosticOrderId");

                    b.HasIndex("DiagnosticOrderItemId");

                    b.HasIndex("Modality");

                    b.HasIndex("PatientId");

                    b.HasIndex("Status");

                    b.ToTable("radiology_studies", "diagnostics");
                });

            modelBuilder.Entity("HospitalManagement.Modules.Diagnostics.Domain.Specimen", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("barcode");

                    b.Property<DateTime?>("CollectedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("collected_at_utc");

                    b.Property<Guid?>("CollectedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("collected_by_user_id");

                    b.Property<string>("CollectionNotes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("collection_notes");

                    b.Property<string>("ContainerType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("container_type");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DiagnosticOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("diagnostic_order_id");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<DateTime?>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<Guid?>("ReceivedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("received_by_user_id");

                    b.Property<DateTime?>("RejectedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rejected_at_utc");

                    b.Property<Guid?>("RejectedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("rejected_by_user_id");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("SpecimenType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("specimen_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("DiagnosticOrderId");

                    b.HasIndex("PatientId");

                    b.HasIndex("Status");

                    b.ToTable("specimens", "diagnostics");
                });

            modelBuilder.Entity("HospitalManagement.Modules.Diagnostics.Domain.SpecimenTransitionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("actor_role");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("from_status");

                    b.Property<string>("Location")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("location");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<Guid>("SpecimenId")
                        .HasColumnType("uuid")
                        .HasColumnName("specimen_id");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("to_status");

                    b.Property<DateTime>("TransitionedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transitioned_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("SpecimenId");

                    b.HasIndex("TransitionedAtUtc");

                    b.ToTable("specimen_transition_events", "diagnostics");
                });

            modelBuilder.Entity("HospitalManagement.Modules.Diagnostics.Domain.DiagnosticOrderItem", b =>
                {
                    b.HasOne("HospitalManagement.Modules.Diagnostics.Domain.DiagnosticOrder", null)
                        .WithMany("Items")
                        .HasForeignKey("DiagnosticOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HospitalManagement.Modules.Diagnostics.Domain.LabCatalogParameter", b =>
                {
                    b.HasOne("HospitalManagement.Modules.Diagnostics.Domain.LabCatalogItem", null)
                        .WithMany("Parameters")
                        .HasForeignKey("LabCatalogItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HospitalManagement.Modules.Diagnostics.Domain.LabResultItem", b =>
                {
                    b.HasOne("HospitalManagement.Modules.Diagnostics.Domain.LabResult", null)
                        .WithMany("Items")
                        .HasForeignKey("LabResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HospitalManagement.Modules.Diagnostics.Domain.SpecimenTransitionEvent", b =>
                {
                    b.HasOne("HospitalManagement.Modules.Diagnostics.Domain.Specimen", null)
                        .WithMany("Transitions")
                        .HasForeignKey("SpecimenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HospitalManagement.Modules.Diagnostics.Domain.DiagnosticOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("HospitalManagement.Modules.Diagnostics.Domain.LabCatalogItem", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("HospitalManagement.Modules.Diagnostics.Domain.LabResult", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("HospitalManagement.Modules.Diagnostics.Domain.Specimen", b =>
                {
                    b.Navigation("Transitions");
                });
#pragma warning restore 612, 618
        }
    }
}
